### ISSUE TITLE
[1.18.2] Flywheel Rendering Crash - Incompatibility with Rubidium and Oculus.

### ISSUE THREAD

**Issue by MokahTGS** [Asek3/Oculus#107]
### Minecraft Version

1.18.2

### Iris Version

oculus-mc1.18.2-1.2.5

### Sodium Version

rubidium-0.5.2a

### Operating System

Win 10

### What is your GPU?

sure

### Java Version

Java 17

### Reproduction Steps

Explore...game crashes

### Crash Report file and latest.log

```shell
https://pastebin.com/JDTKn1nn
```

### Additional context

https://github.com/Jozufozu/Flywheel/issues/136

**Comment by shikyo13** [comment]
Minecraft Version
1.18.2

Iris Version
oculus-mc1.18.2-1.2.5

Sodium Version
rubidium-0.5.2a

Operating System
Win 10

What is your GPU?
RTX 3090

Java Version
Java 17

[crash-2022-06-28_11.30.06-client.txt](https://github.com/Asek3/Oculus/files/9003554/crash-2022-06-28_11.30.06-client.txt)

**Comment by artman41** [comment]
Minecraft Version
1.18.2

Iris Version
oculus-mc1.18.2-1.2.5

Sodium Version
rubidium-0.5.2a

Operating System
Win 10

What is your GPU?
RTX 3080

Java Version
Java 17.0.2

[crash-2022-06-28_23.47.35-client.txt](https://github.com/Asek3/Oculus/files/9005923/crash-2022-06-28_23.47.35-client.txt)

System Details
```
-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.2, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 695431928 bytes (663 MiB) / 3154116608 bytes (3008 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5900X 12-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2206
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1659
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.27
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.27
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 3.27
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 3.27
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 75177.97
	Virtual memory used (MB): 45946.48
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 299.83
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Loaded Shaderpack: ComplementaryShaders_v4.5.zip
		Profile: Custom (+12 options changed by user)
	Launched Version: 1.18.2-forge-40.1.52
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3080/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.59, NVIDIA Corporation
	Window size: 3840x2054
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, quark:emote_resources, file/Slightly-Improved-Font.zip
	Current Language: English (US)
	CPU: 24x AMD Ryzen 9 5900X 12-Core Processor 
```

Error
```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 6/28/22, 11:47 PM
Description: Unexpected error

java.lang.RuntimeException: Cannot use BufferBuilder with format: 9 elements: Position=3,Position,Float Color=4,Vertex Color,Unsigned Byte UV0=2,UV,Float UV2=2,UV,Short Normal=3,Normal,Byte Padding=1,Padding,Byte mc_Entity=2,Generic,Short mc_midTexCoord=2,Generic,Float at_tangent=4,Generic,Byte
	at com.jozufozu.flywheel.core.vertex.BlockVertex.createReader(BlockVertex.java:71) ~[flywheel-forge-1.18-0.6.2.jar%23150!/:1.18-0.6.2] {re:classloading}
	at com.jozufozu.flywheel.core.model.WorldModel.<init>(WorldModel.java:22) ~[flywheel-forge-1.18-0.6.2.jar%23150!/:1.18-0.6.2] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraption.buildLayers(FlwContraption.java:142) ~[create-mc1.18.2_v0.4.1.jar%23113!/:mc1.18.2_v0.4.1] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraption.<init>(FlwContraption.java:54) ~[create-mc1.18.2_v0.4.1.jar%23113!/:mc1.18.2_v0.4.1] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraptionManager.create(FlwContraptionManager.java:84) ~[create-mc1.18.2_v0.4.1.jar%23113!/:mc1.18.2_v0.4.1] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraptionManager.create(FlwContraptionManager.java:22) ~[create-mc1.18.2_v0.4.1.jar%23113!/:mc1.18.2_v0.4.1] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderingWorld.getRenderInfo(ContraptionRenderingWorld.java:94) ~[create-mc1.18.2_v0.4.1.jar%23113!/:mc1.18.2_v0.4.1] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?] {}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderingWorld.tick(ContraptionRenderingWorld.java:67) ~[create-mc1.18.2_v0.4.1.jar%23113!/:mc1.18.2_v0.4.1] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraptionManager.tick(FlwContraptionManager.java:30) ~[create-mc1.18.2_v0.4.1.jar%23113!/:mc1.18.2_v0.4.1] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderDispatcher.tick(ContraptionRenderDispatcher.java:63) ~[create-mc1.18.2_v0.4.1.jar%23113!/:mc1.18.2_v0.4.1] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.events.ClientEvents.onTick(ClientEvents.java:143) ~[create-mc1.18.2_v0.4.1.jar%23113!/:mc1.18.2_v0.4.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1890_ClientEvents_onTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostClientTick(ForgeEventFactory.java:907) ~[forge-1.18.2-40.1.52-universal.jar%23321!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1750) ~[client-1.18.2-20220404.173914-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:blockshot.mixins.json:MixinMinecraft,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:minetogether.mixins.json:MixinMinecraftTitle,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:spyglass_improvements.mixins.json:MinecraftMixin,pl:mixin:APP:tklib.mixin.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1019) ~[client-1.18.2-20220404.173914-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:blockshot.mixins.json:MixinMinecraft,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:minetogether.mixins.json:MixinMinecraftTitle,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:spyglass_improvements.mixins.json:MinecraftMixin,pl:mixin:APP:tklib.mixin.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:blockshot.mixins.json:MixinMinecraft,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:minetogether.mixins.json:MixinMinecraftTitle,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:spyglass_improvements.mixins.json:MinecraftMixin,pl:mixin:APP:tklib.mixin.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23316!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.52.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
```

**Comment by A-T-L-A-S** [comment]
Try turning off your shaders, then, ingame, use `/flywheel backend off` before turning shaders back on.
