### ISSUE TITLE
Enabling Complementary Shaders PBR causes the shader rendering pipeline to crash.

### ISSUE THREAD

**Issue by PenumbraStar** [Asek3/Oculus#119]
### What happened?

As the title says, if you enable PBR, the entire Shader pipeline crashes. Causing shaders to turn off completely and be unable to be reenabled.

### Relevant log output

```shell
[03Jul2022 15:40:09.518] [Render thread/WARN] [Oculus/]: [Triforce Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[03Jul2022 15:40:10.202] [Render thread/ERROR] [Oculus/]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: net.minecraft.server.ChainedJsonException: Invalid shaders/core/terrain_solid.json: Couldn't compile fragment program (<iris shaderpack shaders>, terrain_solid) : 0(2125) : error C1503: undefined variable "vTexCoordL"
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.lambda$new$9(NewWorldRenderingPipeline.java:321) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	at net.coderbot.iris.pipeline.newshader.ShaderMap.<init>(ShaderMap.java:21) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:308) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:629) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	at net.coderbot.iris.Iris.reload(Iris.java:571) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	at net.coderbot.iris.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:27) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:451) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$1(ShaderPackScreen.java:196) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:40) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%230!/:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%236!/:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar%230!/:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:204) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:333) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1066) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.54.jar%2350!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: net.minecraft.server.ChainedJsonException: Invalid shaders/core/terrain_solid.json: Couldn't compile fragment program (<iris shaderpack shaders>, terrain_solid) : 0(2125) : error C1503: undefined variable "vTexCoordL"
	at net.minecraft.server.ChainedJsonException.m_135906_(ChainedJsonException.java:48) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.renderer.ShaderInstance.<init>(ShaderInstance.java:187) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.renderer.ShaderInstance.<init>(ShaderInstance.java:101) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.coderbot.iris.pipeline.newshader.ExtendedShader.<init>(ExtendedShader.java:52) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	at net.coderbot.iris.pipeline.newshader.NewShaderTests.create(NewShaderTests.java:134) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.createShader(NewWorldRenderingPipeline.java:394) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.createShader(NewWorldRenderingPipeline.java:384) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.lambda$new$9(NewWorldRenderingPipeline.java:317) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	... 52 more
Caused by: java.io.IOException: Couldn't compile fragment program (<iris shaderpack shaders>, terrain_solid) : 0(2125) : error C1503: undefined variable "vTexCoordL"
	at com.mojang.blaze3d.shaders.Program.m_166612_(Program.java:72) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at com.mojang.blaze3d.shaders.Program.m_166604_(Program.java:54) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.renderer.ShaderInstance.m_173340_(ShaderInstance.java:223) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.renderer.ShaderInstance.<init>(ShaderInstance.java:172) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.minecraft.client.renderer.ShaderInstance.<init>(ShaderInstance.java:101) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?]
	at net.coderbot.iris.pipeline.newshader.ExtendedShader.<init>(ExtendedShader.java:52) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	at net.coderbot.iris.pipeline.newshader.NewShaderTests.create(NewShaderTests.java:134) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.createShader(NewWorldRenderingPipeline.java:394) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.createShader(NewWorldRenderingPipeline.java:384) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.lambda$new$9(NewWorldRenderingPipeline.java:317) ~[oculus-mc1.18.2-1.2.5.jar%2352!/:1.2.5]
	... 52 more
```

### Minecraft Version

1.18.2

### Iris Version

oculus-mc1.18.2-1.2.5

### Sodium Version

rubidium-0.5.2a

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce RTX 3070 Ti

### Java Version

Eclipse 17.0.3.7-Hotspot

### Additional context

[latest.log](https://github.com/Asek3/Oculus/files/9035400/latest.log)

**Comment by Lolothepro** [comment]
PBR is not supported.

**Comment by Asek3** [comment]
There is no PBR Oculus' builds for now
