### ISSUE TITLE
Unable to compile Complementary (1.16.5)

### ISSUE THREAD

**Issue by Lolothepro** [Asek3/Oculus#133]
### What happened?

Unable to compile Complementary (1.16.5)

### Relevant log output

```shell
[18:54:12] [Render thread/WARN] [ne.co.ir.gl.sh.ProgramCreator/]: Program link log for gbuffers_basic: Vertex info
-----------
0(7) : warning C7533: global variable gl_TextureMatrix is deprecated after version 120
0(693) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(695) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(696) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(698) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(1703) : warning C7555: 'attribute' is deprecated, use 'in/out' instead
0(1704) : warning C7555: 'attribute' is deprecated, use 'in/out' instead
0(1796) : warning C7533: global variable gl_MultiTexCoord2 is deprecated after version 120
0(1799) : warning C7533: global variable gl_NormalMatrix is deprecated after version 120
0(1799) : warning C7533: global variable gl_Normal is deprecated after version 120
0(1801) : warning C7533: global variable gl_Color is deprecated after version 120
0(1816) : warning C7533: global function ftransform is deprecated after version 120

Fragment info
-------------
0(7) : warning C7533: global variable gl_TextureMatrix is deprecated after version 120
0(693) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(695) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(696) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(698) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(905) : warning C7533: global function shadow2D is deprecated after version 120
0(1671) : warning C7533: global variable gl_FragData is deprecated after version 120

[18:54:12] [Render thread/WARN] [ne.co.ir.gl.sh.GlShader/]: Shader compilation log for gbuffers_terrain.vsh: 0(6) : warning C7533: global variable gl_TextureMatrix is deprecated after version 120
0(693) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(694) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(695) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(701) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(703) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(704) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(706) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(714) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(715) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(718) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(721) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(728) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(3028) : warning C7555: 'attribute' is deprecated, use 'in/out' instead
0(3029) : warning C7555: 'attribute' is deprecated, use 'in/out' instead
0(3032) : warning C7555: 'attribute' is deprecated, use 'in/out' instead
0(3220) : warning C7533: global variable gl_ModelViewMatrix is deprecated after version 120
0(3220) : warning C7533: global variable gl_Vertex is deprecated after version 120
0(3229) : warning C7533: global variable gl_MultiTexCoord0 is deprecated after version 120
0(3231) : warning C7533: global variable gl_MultiTexCoord2 is deprecated after version 120
0(3234) : warning C7533: global variable gl_NormalMatrix is deprecated after version 120
0(3234) : warning C7533: global variable gl_Normal is deprecated after version 120
0(3267) : warning C7533: global variable gl_Color is deprecated after version 120
0(4173) : warning C7533: global variable gl_ProjectionMatrix is deprecated after version 120

[18:54:12] [Render thread/WARN] [ne.co.ir.gl.sh.GlShader/]: Shader compilation log for gbuffers_terrain.fsh: 0(6) : warning C7533: global variable gl_TextureMatrix is deprecated after version 120
0(693) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(694) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(695) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(701) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(703) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(704) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(706) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(714) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(715) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(718) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(721) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(728) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(984) : warning C7533: global function shadow2D is deprecated after version 120
0(1865) : error C7531: global function texture2DGradARB requires "#extension GL_ARB_shader_texture_lod : enable" before use
0(2160) : warning C7533: global function texture2DLod is deprecated after version 120
0(2988) : warning C7533: global variable gl_FragData is deprecated after version 120

[18:54:12] [Render thread/ERROR] [Oculus/]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: Shader compilation failed!
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.createPass(DeferredWorldRenderingPipeline.java:550) ~[oculus:?] {re:classloading}
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.lambda$new$1(DeferredWorldRenderingPipeline.java:296) ~[oculus:?] {re:classloading}
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?] {}
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.lambda$new$2(DeferredWorldRenderingPipeline.java:277) ~[oculus:?] {re:classloading}
	at net.coderbot.iris.gbuffer_overrides.matching.ProgramTable.<init>(ProgramTable.java:16) ~[oculus:?] {re:classloading}
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.<init>(DeferredWorldRenderingPipeline.java:260) ~[oculus:?] {re:classloading}
	at net.coderbot.iris.Iris.createPipeline(Iris.java:639) ~[oculus:?] {re:mixin,re:classloading}
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[oculus:?] {re:mixin,re:classloading}
	at net.coderbot.iris.Iris.reload(Iris.java:582) ~[oculus:?] {re:mixin,re:classloading}
	at net.coderbot.iris.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:27) ~[oculus:?] {re:classloading}
	at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:449) ~[oculus:?] {re:classloading,re:mixin}
	at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$1(ShaderPackScreen.java:194) ~[oculus:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:181) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:180) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.json:MixinRenderSystem,pl:mixin:A}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:306) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:997) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.35-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?] {}
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?] {}
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?] {}
Caused by: java.lang.RuntimeException: Failed to compile FRAGMENT shader for program gbuffers_terrain.fsh
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:78) ~[oculus:?] {re:classloading}
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[oculus:?] {re:classloading}
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.createPass(DeferredWorldRenderingPipeline.java:546) ~[oculus:?] {re:classloading}
	... 53 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:40) ~[oculus:?] {re:classloading}
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:21) ~[oculus:?] {re:classloading}
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:76) ~[oculus:?] {re:classloading}
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[oculus:?] {re:classloading}
	at net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.createPass(DeferredWorldRenderingPipeline.java:546) ~[oculus:?] {re:classloading}
	... 53 more
```

### Minecraft Version

1.16.5

### Iris Version

Oculus 1.2.5

### Sodium Version

Rubidium 0.2.7

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

### Java Version

Java 17

**Comment by Asek3** [comment]
Should be fixed in 1.4 versions
