### ISSUE TITLE
[1.18.1]not working

### ISSUE THREAD

**Issue by windy664** [Asek3/Oculus#159]
### Minecraft Version

Minecraft 1.18.1

### Iris Version

oculus-mc1.18.1-1.2.1.jar

### Sodium Version

rubidium-0.5.0.jar

### Operating System

Windows11

### What is your GPU?

NVIDIA GeForce MX150

### Java Version

Java 17

### Reproduction Steps

1.put the mod in game
2.start Minecraft

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// My bad.

Time: 2022/8/18 下午9:04
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.1-39.1.2-universal.jar%23116!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:169) ~[forge-1.18.1-39.1.2-universal.jar%23116!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:554) ~[client-1.18.1-20211210.034407-srg.jar%23112!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.oculus.json:MixinMinecraft,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineDestruction,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:409) ~[client-1.18.1-20211210.034407-srg.jar%23112!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:548) ~[client-1.18.1-20211210.034407-srg.jar%23112!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.oculus.json:MixinMinecraft,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineDestruction,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.18.1-20211210.034407-srg.jar%23112!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:875) ~[client-1.18.1-20211210.034407-srg.jar%23112!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1041) ~[client-1.18.1-20211210.034407-srg.jar%23112!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.oculus.json:MixinMinecraft,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineDestruction,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:661) ~[client-1.18.1-20211210.034407-srg.jar%23112!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.oculus.json:MixinMinecraft,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineDestruction,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23112!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.1.2.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.coderbot.iris.compat.flywheel.FlywheelCompat.disableBackend(FlywheelCompat.java:11) ~[oculus-mc1.18.1-1.2.1.jar%23110!/:1.0] {re:classloading}
-- MOD oculus --
Details:
	Mod File: oculus-mc1.18.1-1.2.1.jar
	Failure message: Oculus (oculus) encountered an error during the sided_setup event phase
		java.lang.NoSuchMethodError: 'void com.jozufozu.flywheel.config.FlwEngine.handle(com.jozufozu.flywheel.config.FlwEngine)'
	Mod Version: 1.2.1
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchMethodError: 'void com.jozufozu.flywheel.config.FlwEngine.handle(com.jozufozu.flywheel.config.FlwEngine)'
Stacktrace:
	at net.coderbot.iris.compat.flywheel.FlywheelCompat.disableBackend(FlywheelCompat.java:11) ~[oculus-mc1.18.1-1.2.1.jar%23110!/:1.0] {re:classloading}
	at net.coderbot.iris.Iris.onInitializeClient(Iris.java:103) ~[oculus-mc1.18.1-1.2.1.jar%23110!/:1.0] {re:mixin,re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.18.1-39.1.2.jar%23114!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.18.1-39.1.2.jar%23113!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 654205920 bytes (623 MiB) / 1476395008 bytes (1408 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5917
	Graphics card #0 versionInfo: DriverVersion=26.20.100.7985
	Graphics card #1 name: NVIDIA GeForce MX150
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x1d10
	Graphics card #1 versionInfo: DriverVersion=30.0.15.1215
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: LPDDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: LPDDR3
	Virtual memory max (MB): 16095.78
	Virtual memory used (MB): 12633.19
	Swap memory total (MB): 8047.89
	Swap memory used (MB): 679.10
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Loaded Shaderpack: (off)
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		[选装][崩溃优化]notenoughcrashes-4.1.4+1.18.1-forge.jar |Not Enough Crashes            |notenoughcrashes              |4.1.4+1.18.1        |ENQUEUE_IM|Manifest: NOSIGNATURE
		[全能植物魔法]AIOTBotania-1.18.1-2.0.2.jar              |AIOT Botania                  |aiotbotania                   |1.18.1-2.0.2        |ENQUEUE_IM|Manifest: NOSIGNATURE
		[NPC]flashnpcs-1.18.1-1.1.4v2.jar                 |Flash's NPCs                  |flashnpcs                     |1.1.4v2             |ENQUEUE_IM|Manifest: NOSIGNATURE
		[公共GUI]Public+GUI+Announcement-forge-1.18.1-3.2.0.|Public GUI Announcement       |publicguiannouncement         |1.1.0.1             |ENQUEUE_IM|Manifest: NOSIGNATURE
		[JEI]jei-1.18.1-9.4.1.172.jar                     |Just Enough Items             |jei                           |9.4.1.172           |ENQUEUE_IM|Manifest: NOSIGNATURE
		rubidium-0.5.0.jar                                |Rubidium                      |rubidium                      |0.5.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		[叶间穿行]PassableFoliage-1.18-forge-3.0.0.jar        |Passable Foliage              |passablefoliage               |3.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		[选装][世界地图]XaerosWorldMap_1.20.3.1_Forge_1.18.jar  |Xaero's World Map             |xaeroworldmap                 |1.20.3.1            |ENQUEUE_IM|Manifest: NOSIGNATURE
		[选装][自动汉化更新]i18nupdatemod-1.18-3.0.0.jar          |I18n update Mod               |i18nupdatemod                 |3.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		[中式剑]arsenal_core-1.1.2-1.18.1.jar                |Arsenal Core                  |arsenal_core                  |1.1.2-1.18.1        |ENQUEUE_IM|Manifest: NOSIGNATURE
		[静谧四季]SereneSeasons-1.18.1-6.0.0.11-universal.jar |Serene Seasons                |sereneseasons                 |1.18.1-6.0.0.11     |ENQUEUE_IM|Manifest: NOSIGNATURE
		[前置]LibX-1.18.1-3.1.18.jar                        |LibX                          |libx                          |1.18.1-3.1.18       |ENQUEUE_IM|Manifest: NOSIGNATURE
		[烹饪锅]CrockPot-1.18.1-1.1.1-release.jar            |Crock Pot                     |crockpot                      |1.1.1-release       |ENQUEUE_IM|Manifest: NOSIGNATURE
		[载入DFU]lazydfu-1.0-1.18+.jar                      |LazyDFU                       |lazydfu                       |0.1.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		[选装][更好的视距加载]farsight-1.18-1.6.jar                |Farsight mod                  |farsight_view                 |1.18-1.6            |ENQUEUE_IM|Manifest: NOSIGNATURE
		[选装][FPS减速器]FpsReducer2-forge-1.18.2-2.0.jar      |FPS Reducer                   |fpsreducer                    |1.18.2-2.0          |ENQUEUE_IM|Manifest: NOSIGNATURE
		[无线终端前置]cloth-config-6.2.62-forge.jar             |Cloth Config v4 API           |cloth_config                  |6.2.62              |ENQUEUE_IM|Manifest: NOSIGNATURE
		[AE2AO]ae2ao-6.0.0-1.18.1.jar                     |AE2AO                         |ae2ao                         |6.0.0-1.18.1        |ENQUEUE_IM|Manifest: NOSIGNATURE
		[机械奶茶]createcafe-1.2-1.18.1.jar                   |Create Cafe                   |createcafe                    |1.2-1.18.1          |ENQUEUE_IM|Manifest: NOSIGNATURE
		[工业]indreb-1.18.1-0.12.4.jar                      |Industrial Reborn             |indreb                        |1.18.1-0.12.4       |ENQUEUE_IM|Manifest: NOSIGNATURE
		[更多箱子]ironchest-1.18-13.0.7.jar                   |Iron Chests                   |ironchest                     |1.18-13.0.7         |ENQUEUE_IM|Manifest: NOSIGNATURE
		[神话植物学]MythicBotany-1.18.1-2.0.2.jar              |MythicBotany                  |mythicbotany                  |1.18.1-2.0.2        |ENQUEUE_IM|Manifest: NOSIGNATURE
		[选装][更加的延迟显示]BetterPingDisplay-1.18.1-1.1.jar     |Better Ping Display           |betterpingdisplay             |1.1                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |ENQUEUE_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		[农夫乐事]FarmersDelight-1.18.1-1.0.4.jar             |Farmer's Delight              |farmersdelight                |1.18.1-1.0.4        |ENQUEUE_IM|Manifest: NOSIGNATURE
		[Ti]titanium-1.18-3.4.1-31.jar                    |Titanium                      |titanium                      |3.4.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		[沉浸工程]ImmersiveEngineering-1.18.1-7.1.0-145.jar   |Immersive Engineering         |immersiveengineering          |1.18.1-7.1.0-145    |ENQUEUE_IM|Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		[选装][玉]Jade-1.18.1-4.4.1.jar                      |Jade                          |jade                          |4.4.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		[应用能源2]appliedenergistics2-10.1.0-beta.2.jar      |Applied Energistics 2         |ae2                           |10.1.0-beta.2       |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.18.1-39.1.2-universal.jar                 |Forge                         |forge                         |39.1.2              |ENQUEUE_IM|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		[选装][点歌][forge-1.18]AllMusic-2.5.11.jar           |AllMusic                      |allmusic                      |2.5.11              |ENQUEUE_IM|Manifest: NOSIGNATURE
		[植物魔法]Botania-1.18.1-429.jar                      |Botania                       |botania                       |1.18.1-429          |ENQUEUE_IM|Manifest: NOSIGNATURE
		[桥]sushigocrafting-1.18.1-0.3.2.jar               |Sushi Go Crafting             |sushigocrafting               |0.3.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		[石粒]ThisRocks-1.18.1-1.0.0.jar                    |This Rocks! (Forge)           |rocks                         |1.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		[选装][更好的FPS]betterfpsdist-1.18.2-1.5.jar          |betterfpsdist mod             |betterfpsdist                 |1.18.2-1.5          |ENQUEUE_IM|Manifest: NOSIGNATURE
		[妖怪之山通用库]mmlib-1.0.0-1.18.1.jar                   |Mysterious Mountain Lib       |mmlib                         |1.0.0-1.18.1        |ENQUEUE_IM|Manifest: NOSIGNATURE
		[饰品栏]curios-forge-1.18.1-5.0.6.2.jar              |Curios API                    |curios                        |1.18.1-5.0.6.2      |ENQUEUE_IM|Manifest: NOSIGNATURE
		[飞轮]flywheel-forge-1.18-0.6.1.jar                 |Flywheel                      |flywheel                      |1.18-0.6.1.63       |ENQUEUE_IM|Manifest: NOSIGNATURE
		[机械动力]create-mc1.18.1_v0.4f.jar                   |Create                        |create                        |0.4f                |ENQUEUE_IM|Manifest: NOSIGNATURE
		[帕秋莉手册]Patchouli-1.18.1-65.jar                    |Patchouli                     |patchouli                     |1.18.1-65           |ENQUEUE_IM|Manifest: NOSIGNATURE
		oculus-mc1.18.1-1.2.1.jar                         |Oculus                        |oculus                        |1.2.1               |ERROR     |Manifest: NOSIGNATURE
		[选装][迷你地图]Xaeros_Minimap_22.3.0_Forge_1.18.jar    |Xaero's Minimap               |xaerominimap                  |22.3.0              |ENQUEUE_IM|Manifest: NOSIGNATURE
		[作物胜景]Croptopia-1.18-FORGE-1.8.3.jar              |Croptopia                     |croptopia                     |1.8.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		[灵灾]malum-1.18.1-1.3.5.jar                        |Malum                         |malum                         |1.18.1-1.3.5        |ENQUEUE_IM|Manifest: NOSIGNATURE
		[魔法艺术3]mna-1.7.1.20.jar                           |Mana and Artifice             |mna                           |1.7.1.20            |ENQUEUE_IM|Manifest: NOSIGNATURE
		[选装][通用拼音搜索]JustEnoughCharacters-1.18.1-4.3.3.jar |Just Enough Characters        |jecharacters                  |1.18.1-4.3.3        |ENQUEUE_IM|Manifest: NOSIGNATURE
		[神秘遗物]EnigmaticLegacy-2.17.3.jar                  |Enigmatic Legacy              |enigmaticlegacy               |2.17.3              |ENQUEUE_IM|Manifest: NOSIGNATURE
		[选装][苹果皮]appleskin-forge-mc1.18-2.4.0.jar         |AppleSkin                     |appleskin                     |2.4.0+mc1.18        |ENQUEUE_IM|Manifest: NOSIGNATURE
		[无线终端前置]architectury-3.9.66.jar                   |Architectury                  |architectury                  |3.9.66              |ENQUEUE_IM|Manifest: NOSIGNATURE
		[无线终端]AE2WTLib-10.1.1-beta.6.jar                  |AE2WTLib                      |ae2wtlib                      |10.1.1-beta.6       |ENQUEUE_IM|Manifest: NOSIGNATURE
		[家具]furniture-7.0.0-pre28-1.18.1.jar              |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre28         |ENQUEUE_IM|Manifest: NOSIGNATURE
		[太阳能头盔]SolarHelmet-1.18-38.0.0.jar                |SolarHelmet                   |solarhelmet                   |38.0.0              |ENQUEUE_IM|Manifest: NOSIGNATURE
		[工程师的装饰]engineersdecor-1.18.1-1.1.21.jar          |Engineer's Decor              |engineersdecor                |1.1.21              |ENQUEUE_IM|Manifest: bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		[FC]ferritecore-4.1.2-forge.jar                   |Ferrite Core                  |ferritecore                   |4.1.2               |ENQUEUE_IM|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		[玉米乐事]corn_delight-1.0.8-1.18.1.jar               |Corn Delight                  |corn_delight                  |1.0.8-1.18.1        |ENQUEUE_IM|Manifest: NOSIGNATURE
		[选装][现代化UI]ModernUI-1.18.1-3.4.0.99-universal.jar |Modern UI                     |modernui                      |3.4.0.99            |ENQUEUE_IM|Manifest: 72:da:aa:fa:02:98:8b:71:b7:c5:ce:aa:0f:0d:cb:a3:ac:4b:97:d4:bc:fa:58:e6:98:e1:2e:ca:f4:61:a2:b0
		[选装][耐久显示]durabilityviewer-1.18.1-forge39.0.9-1.10|Giselbaers Durability Viewer  |durabilityviewer              |1.18.1-forge39.0.9-1|ENQUEUE_IM|Manifest: NOSIGNATURE
		[贴图]texturesmod-2.2.jar                           |Texturesmod                   |texturesmod                   |0.0NONE             |ENQUEUE_IM|Manifest: NOSIGNATURE
		[选装][更好的mod显示]BetterModsButton-v3.1.0-1.18.1-Forge|Better Mods Button            |bettermodsbutton              |3.1.0               |ENQUEUE_IM|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		[前置]geckolib-1.18-forge-3.0.11.jar                |GeckoLib                      |geckolib3                     |3.0.11              |ENQUEUE_IM|Manifest: NOSIGNATURE
		[机械动力附加]createaddition-1.18.1-20220420a.jar       |Create Crafts & Additions     |createaddition                |1.18.1-20220420a    |ENQUEUE_IM|Manifest: NOSIGNATURE
		[循环]Cyclic-1.18.1-1.6.15.jar                      |Cyclic                        |cyclic                        |1.18.1-1.6.15       |ENQUEUE_IM|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
	Crash Report UUID: a1a1e42f-7316-4427-a2f2-a6b627193983
	Flywheel Backend: GL33 Instanced Arrays
	FML: 39.1
	Forge: net.minecraftforge:39.1.2
	Suspected Mods: Minecraft (minecraft), Forge (forge)
```

**Comment by Asek3** [comment]
1.18.1 is not supported
