### ISSUE TITLE
Shaders not loading

### ISSUE THREAD

**Issue by deadspidervenom** [Asek3/Oculus#172]
### What happened?

Ive tried loading different shaders but nothing will load

### Minecraft Version

1.18.2

### Iris Version

1.2.5a

### Sodium Version

0.5.3a

### Operating System

windows 10

### What is your GPU?

nvidia gtx 1660 super

### Java Version

java  17.0.1

### Additional context

`[09:25:15] [Render thread/INFO] [Oculus/]: Destroying pipeline OVERWORLD
[09:25:15] [Render thread/WARN] [Oculus/]: Custom texture directive for stage composite, sampler depthtex2.1 contains more parts than we expected: /lib/IMG/worley3d.dat TEXTURE_3D RGB8 128 128 128 RGB UNSIGNED_BYTE
[09:25:15] [Render thread/ERROR] [Oculus/]: Invalid alpha test directive for shadow: true
[09:25:15] [Render thread/WARN] [Oculus/]: Invalid pack option: Barrel_Distortion
[09:25:15] [Render thread/WARN] [Oculus/]: Invalid pack option: Refrection_Strength
[09:25:15] [Render thread/WARN] [Oculus/]: Invalid pack option: Film_Saturation
[09:25:15] [Render thread/WARN] [Oculus/]: Unable to resolve shader pack option menu element "Ambient_Occlusion_Amount" defined in shaders.properties
[09:25:15] [Render thread/WARN] [Oculus/]: Unable to resolve shader pack option menu element "Barrel_Distortion" defined in shaders.properties
[09:25:15] [Render thread/WARN] [Oculus/]: Unable to resolve shader pack option menu element "<mpty>" defined in shaders.properties
[09:25:15] [Render thread/WARN] [Oculus/]: Unable to resolve shader pack option menu element "Film_Saturation" defined in shaders.properties
[09:25:15] [Render thread/WARN] [Oculus/]: Unable to resolve shader pack option menu element "Spatial_Filter" defined in shaders.properties
[09:25:15] [Render thread/WARN] [Oculus/]: Unable to resolve shader pack option menu element "CRT_Border" defined in shaders.properties
[09:25:15] [Render thread/WARN] [Oculus/]: Unable to resolve shader pack option menu element "About" defined in shaders.properties
[09:25:15] [Render thread/WARN] [Oculus/]: Unable to resolve shader pack option menu element "AP1" defined in shaders.properties
[09:25:15] [Render thread/INFO] [Oculus/]: Profile: Custom (+0 options changed by user)
[09:25:16] [Render thread/INFO] [Oculus/]: Using shaderpack: MollyVX-8-21-2022.zip
[09:25:16] [Render thread/INFO] [Oculus/]: Creating pipeline for dimension OVERWORLD
[09:25:16] [Render thread/WARN] [ne.co.ir.gl.sh.GlShader/]: Shader compilation log for deferred.fsh: 0(1356) : error C7599: (location = 0, component = 0) already used

[09:25:16] [Render thread/ERROR] [Oculus/]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: Shader compilation failed!
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:235) ~[oculus-mc1.18.2-1.2.5a.jar%23133!/:1.2.5] {re:classloading}
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:93) ~[oculus-mc1.18.2-1.2.5a.jar%23133!/:1.2.5] {re:classloading}
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:216) ~[oculus-mc1.18.2-1.2.5a.jar%23133!/:1.2.5] {re:classloading}
	at net.coderbot.iris.Iris.createPipeline(Iris.java:632) ~[oculus-mc1.18.2-1.2.5a.jar%23133!/:1.2.5] {re:mixin,re:classloading}
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[oculus-mc1.18.2-1.2.5a.jar%23133!/:1.2.5] {re:mixin,re:classloading}
	at net.coderbot.iris.Iris.reload(Iris.java:574) ~[oculus-mc1.18.2-1.2.5a.jar%23133!/:1.2.5] {re:mixin,re:classloading}
	at net.coderbot.iris.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:27) ~[oculus-mc1.18.2-1.2.5a.jar%23133!/:1.2.5] {re:classloading}
	at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:451) ~[oculus-mc1.18.2-1.2.5a.jar%23133!/:1.2.5] {re:classloading,re:mixin}
	at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$1(ShaderPackScreen.java:196) ~[oculus-mc1.18.2-1.2.5a.jar%23133!/:1.2.5] {re:classloading,re:mixin}
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:40) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:fancymenu.general.mixin.json:MixinWidget,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:mixin,xf:fml:seamless_loading_screen:MouseHandler#turnPlayer,pl:runtimedistcleaner:A,re:classloading,xf:fml:seamless_loading_screen:MouseHandler#turnPlayer,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:debugify-common.mixins.json:basic.client.mc121772.MouseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:mixin,xf:fml:seamless_loading_screen:MouseHandler#turnPlayer,pl:runtimedistcleaner:A,re:classloading,xf:fml:seamless_loading_screen:MouseHandler#turnPlayer,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:debugify-common.mixins.json:basic.client.mc121772.MouseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:mixin,xf:fml:seamless_loading_screen:MouseHandler#turnPlayer,pl:runtimedistcleaner:A,re:classloading,xf:fml:seamless_loading_screen:MouseHandler#turnPlayer,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:debugify-common.mixins.json:basic.client.mc121772.MouseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:mixin,xf:fml:seamless_loading_screen:MouseHandler#turnPlayer,pl:runtimedistcleaner:A,re:classloading,xf:fml:seamless_loading_screen:MouseHandler#turnPlayer,pl:mixin:APP:balm.mixins.json:MouseHandlerAccessor,pl:mixin:APP:debugify-common.mixins.json:basic.client.mc121772.MouseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%230!/:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%236!/:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar%230!/:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.json:MixinGlStateManager,pl:mixin:APP:mixins.oculus.json:MixinRenderSystem,pl:mixin:APP:mixins.oculus.json:statelisteners.MixinRenderSystem,pl:mixin:APP:debugify-common.mixins.json:basic.client.mc122477.RenderSystemMixin,pl:mixin:APP:flywheel.mixins.json:RenderTexturesMixin,pl:mixin:A}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:333) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1067) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:debugify-common.mixins.json:basic.client.mc46766.MinecraftClientMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:drippyloadingscreen.mixin.json:MixinMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:fancymenu.general.mixin.json:IMixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:664) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:debugify-common.mixins.json:basic.client.mc46766.MinecraftClientMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:drippyloadingscreen.mixin.json:MixinMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:fancymenu.general.mixin.json:IMixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23170!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.73.jar%2351!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?] {}
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?] {}
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?] {}
Caused by: java.lang.RuntimeException: Failed to compile FRAGMENT shader for program deferred.fsh
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:78) ~[oculus-mc1.18.2-1.2.5a.jar%23133!/:1.2.5] {re:classloading}
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[oculus-mc1.18.2-1.2.5a.jar%23133!/:1.2.5] {re:classloading}
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:231) ~[oculus-mc1.18.2-1.2.5a.jar%23133!/:1.2.5] {re:classloading}
	... 53 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:40) ~[oculus-mc1.18.2-1.2.5a.jar%23133!/:1.2.5] {re:classloading}
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:21) ~[oculus-mc1.18.2-1.2.5a.jar%23133!/:1.2.5] {re:classloading}
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:76) ~[oculus-mc1.18.2-1.2.5a.jar%23133!/:1.2.5] {re:classloading}
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[oculus-mc1.18.2-1.2.5a.jar%23133!/:1.2.5] {re:classloading}
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:231) ~[oculus-mc1.18.2-1.2.5a.jar%23133!/:1.2.5] {re:classloading}
	... 53 more`

**Comment by deadspidervenom** [comment]
Seems to be a conflict with another mod, idk which but i am trying to figure it out.
