### ISSUE TITLE
Server need to load Oculus (both-side mod but not a client side)

### ISSUE THREAD

**Issue by Sam-Chai** [Asek3/Oculus#265]
### What happened?

Here it is:
When I join my server with Oculus, then reports me a BIG RED CROSS (in screenshot shows), but I can join my server normally. And I see client log, they reports me this:
`[Netty Client IO #1/INFO]: Client has mods that are missing on server: [oculus]`
What the? When I install Oculus on my server to try solve this problem, the server crashed.
crash-reports:
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2022/12/29 下午3:13
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.1.80-universal.jar%23117!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.18.2-40.1.80-universal.jar%23117!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23112!/:?] {re:classloading,pl:accesstransformer:B}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.1.80.jar%2319!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%237!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%237!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%237!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%237!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%237!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%237!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%237!/:?] {}
	at io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:41) [arclight-forge-1.18.2-1.0.7.jar%231!/:arclight-1.18.2-1.0.7-40114eb5] {}
	at io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:12) [arclight-forge-1.18.2-1.0.7.jar%231!/:arclight-1.18.2-1.0.7-40114eb5] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23) [arclight-forge-1.18.2-1.0.7.jar:arclight-1.18.2-1.0.7-40114eb5] {}
	at io.izzel.arclight.server.Launcher.main(Launcher.java:18) [arclight-forge-1.18.2-1.0.7.jar:arclight-1.18.2-1.0.7-40114eb5] {}

```
So, I think the Oculus seems like use some server-side class or method, and it need server-side runtime. But it just a client mod, cannot be installed on the server.
Hope to solve this problem, make the client do not report missing on the server warn, and give me a green right on my server's motd.

### Screenshots

![image](https://user-images.githubusercontent.com/29940426/209918539-27e67491-fd1c-4007-906e-c3dedf975f6a.png)

### Relevant log output

```shell
Client log:

[15:11:54] [Netty Client IO #1/INFO]: Client has mods that are missing on server: [oculus]
```
Server crash-report
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2022/12/29 下午3:13
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.1.80-universal.jar%23117!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.18.2-40.1.80-universal.jar%23117!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23112!/:?] {re:classloading,pl:accesstransformer:B}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.1.80.jar%2319!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%237!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%237!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%237!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%237!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%237!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%237!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%237!/:?] {}
	at io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:41) [arclight-forge-1.18.2-1.0.7.jar%231!/:arclight-1.18.2-1.0.7-40114eb5] {}
	at io.izzel.arclight.boot.application.ApplicationBootstrap.accept(ApplicationBootstrap.java:12) [arclight-forge-1.18.2-1.0.7.jar%231!/:arclight-1.18.2-1.0.7-40114eb5] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.izzel.arclight.boot.application.Main_Forge.main(Main_Forge.java:23) [arclight-forge-1.18.2-1.0.7.jar:arclight-1.18.2-1.0.7-40114eb5] {}
	at io.izzel.arclight.server.Launcher.main(Launcher.java:18) [arclight-forge-1.18.2-1.0.7.jar:arclight-1.18.2-1.0.7-40114eb5] {}

```
```


### Minecraft Version

1.18.2

### Oculus Version

oculus-1.4.3.jar

### Rubidium Version

rubidium-0.5.4.jar

### Operating System

Server: Windows 10, Client: Windows 11

### What is your GPU?

RTX 2060

### Java Version

Java 17

### Additional context

Oculus just need change it to just client-side mod is ok. Not both-side

**Comment by DtnX** [comment]
try to use [Better Compatibility Checker](https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker)
