### ISSUE TITLE
Game crash when sometimes load new chunk

### ISSUE THREAD

**Issue by exdj158** [Asek3/Oculus#276]
### Minecraft Version

1.19.2

### Oculus Version

oculus-mc1.19.2-1.2.8a

### Sodium Version

rubidium-0.6.2

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 3080

### Java Version

Java 17

### Reproduction Steps

Game Crashes

### Crash Report file and latest.log

```shell
[13:42:03] [Sound engine/ERROR]: Allocate new source: Invalid parameter parameter value.
[13:42:07] [Render thread/WARN]: Can't get entityTexture for betteranimalsplus:textures/entity_icon/boar_gray.png
[13:42:07] [Render thread/WARN]: Can't get entityTexture for betteranimalsplus:textures/entity_icon/boar_dark_brown.png
[13:42:07] [Server thread/WARN]: defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityBearNeutral from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
[13:42:08] [Server thread/INFO]: [APTweaks:Core] ↓ Server load changed from LOW (avg. 25.981266021728516) to VERY_LOW (avg. 16.101318359375)
[13:42:10] [Server thread/WARN]: defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityLammergeier from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
[13:42:10] [Server thread/WARN]: defineId called for: class dev.itsmeow.betteranimalsplus.common.entity.EntityFeralWolf from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
[13:42:10] [Render thread/WARN]: Received passengers for unknown entity
[13:42:13] [Render thread/WARN]: Can't get entityTexture for guardvillagers:textures/entity_icon/guard/guard_0.png
[13:42:16] [Render thread/WARN]: Can't get entityTexture for takesapillage:textures/entity_icon/clay_golem/clay_golem.png
[13:42:20] [Render thread/ERROR]: Unreported exception thrown!
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413) ~[?:?]
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118) ~[?:?]
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.findNext(WorkStealingFutureDrain.java:47) ~[rubidium-0.6.2.jar%23609!/:?]
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.hasNext(WorkStealingFutureDrain.java:28) ~[rubidium-0.6.2.jar%23609!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.setupUploadBatches(RenderRegionManager.java:123) ~[rubidium-0.6.2.jar%23609!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:59) ~[rubidium-0.6.2.jar%23609!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:327) ~[rubidium-0.6.2.jar%23609!/:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:196) ~[rubidium-0.6.2.jar%23609!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_194338_(LevelRenderer.java:5708) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at net.minecraft.client.renderer.LevelRenderer.invokeSetupRender(LevelRenderer.java) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:382) ~[oculus-mc1.19.2-1.2.8a.jar%23586!/:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:631) ~[oculus-mc1.19.2-1.2.8a.jar%23586!/:?]
	at net.minecraft.client.renderer.LevelRenderer.handler$zlj000$iris$renderTerrainShadows(LevelRenderer.java:9661) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1158) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.3.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at it.unimi.dsi.fastutil.objects.Object2ObjectArrayMap.get(Object2ObjectArrayMap.java:331) ~[fastutil-8.5.6.jar%23127!/:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectMap.computeIfAbsent(Object2ObjectMap.java:361) ~[fastutil-8.5.6.jar%23127!/:?]
	at net.mehvahdjukaar.moonlight.api.client.model.forge.ExtraModelDataImpl$Builder.with(ExtraModelDataImpl.java:49) ~[moonlight-1.19.2-2.1.25-forge.jar%23572!/:?]
	at net.mehvahdjukaar.supplementaries.common.block.tiles.SwayingBlockTile.getExtraModelData(SwayingBlockTile.java:69) ~[supplementaries-1.19.2-2.2.34b.jar%23636!/:?]
	at net.mehvahdjukaar.moonlight.api.client.model.IExtraModelDataProvider.getModelData(IExtraModelDataProvider.java:535) ~[moonlight-1.19.2-2.1.25-forge.jar%23572!/:?]
	at net.minecraftforge.client.model.data.ModelDataManager.refreshAt(ModelDataManager.java:65) ~[forge-1.19.2-43.2.3-universal.jar%23674!/:?]
	at net.minecraftforge.client.model.data.ModelDataManager.getAt(ModelDataManager.java:83) ~[forge-1.19.2-43.2.3-universal.jar%23674!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:79) ~[rubidium-0.6.2.jar%23609!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:266) ~[rubidium-0.6.2.jar%23609!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.stealTask(ChunkBuilder.java:229) ~[rubidium-0.6.2.jar%23609!/:?]
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.findNext(WorkStealingFutureDrain.java:54) ~[rubidium-0.6.2.jar%23609!/:?]
	... 30 more
[13:42:21] [Server thread/INFO]: Stopping server
[13:42:21] [Server thread/INFO]: Saving players
[13:42:21] [Server thread/INFO]: Saving worlds
```

```
[00:34:10] [Sound engine/ERROR]: Stop: Invalid parameter parameter value.
[00:34:20] [Render thread/ERROR]: Unreported exception thrown!
java.nio.BufferUnderflowException: null
	at me.jellysquid.mods.sodium.client.gl.util.MultiDrawBatch$UnsafeMultiDrawBatch.add(MultiDrawBatch.java:155) ~[rubidium-0.6.2.jar%23609!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.addDrawCall(RegionChunkRenderer.java:190) ~[rubidium-0.6.2.jar%23609!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.redirect$coe000$cullleaves$fixTransparentBlockFaceCulling(RegionChunkRenderer.java:2057) ~[rubidium-0.6.2.jar%23609!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.buildDrawBatches(RegionChunkRenderer.java:113) ~[rubidium-0.6.2.jar%23609!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:82) ~[rubidium-0.6.2.jar%23609!/:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:294) ~[rubidium-0.6.2.jar%23609!/:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:220) ~[rubidium-0.6.2.jar%23609!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java:5691) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at net.minecraft.client.renderer.LevelRenderer.invokeRenderChunkLayer(LevelRenderer.java) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:422) ~[oculus-mc1.19.2-1.2.8a.jar%23586!/:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:631) ~[oculus-mc1.19.2-1.2.8a.jar%23586!/:?]
	at net.minecraft.client.renderer.LevelRenderer.handler$zlj000$iris$renderTerrainShadows(LevelRenderer.java:9661) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1158) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.3.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
[00:34:22] [Server thread/INFO]: Stopping server
[00:34:22] [Server thread/INFO]: Saving players
[00:34:22] [Server thread/INFO]: Saving worlds
```

**Comment by LKD-PIX** [comment]
I am experiencing this aswell.
Any updates on this?
