### ISSUE TITLE
Incompatible with Flywheel 0.6.1

### ISSUE THREAD

**Issue by CDAGaming** [Asek3/Oculus#29]
Title.

```
Caught exception during event FMLClientSetupEvent dispatch for modid oculus
java.lang.NoSuchMethodError: 'void com.jozufozu.flywheel.config.FlwEngine.handle(com.jozufozu.flywheel.config.FlwEngine)'
	at TRANSFORMER/oculus@1.2.1/net.coderbot.iris.compat.flywheel.FlywheelCompat.disableBackend(FlywheelCompat.java:11)
	at TRANSFORMER/oculus@1.2.1/net.coderbot.iris.Iris.onInitializeClient(Iris.java:103)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18.1-39.1.0/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
	at LAYER PLUGIN/fmlcore@1.18.1-39.1.0/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Asek3** [comment]
c64b6999fc132c4f5e269d93767a026de71aac5d
