### ISSUE TITLE
Unable to compile shaders for UShader, Arc

### ISSUE THREAD

**Issue by shal0l** [Asek3/Oculus#294]
### What happened?

No other mods installed.

### Relevant log output

```shell
[17:55:58] [Render thread/INFO]: Destroying pipeline OVERWORLD
[17:55:58] [Render thread/WARN]: Per-buffer pass blending directives are not supported, ignoring blend directive for blend.gbuffers_water.colortex1
[17:55:58] [Render thread/WARN]: Per-buffer pass blending directives are not supported, ignoring blend directive for blend.gbuffers_water.colortex2
[17:55:58] [Render thread/WARN]: Per-buffer pass blending directives are not supported, ignoring blend directive for blend.gbuffers_water.colortex3
[17:55:58] [Render thread/WARN]: Custom texture directive for stage deferred, sampler depthtex1 contains more parts than we expected: image/curl3D.dat TEXTURE_3D RGB8 64 64 64 RGB UNSIGNED_BYTE
[17:55:58] [Render thread/WARN]: Custom texture directive for stage prepare, sampler depthtex1 contains more parts than we expected: image/curl3D.dat TEXTURE_3D RGB8 64 64 64 RGB UNSIGNED_BYTE
[17:55:58] [Render thread/WARN]: Unable to resolve shader pack option menu element "planetRadiusScale" defined in shaders.properties
[17:55:58] [Render thread/WARN]: Unable to resolve shader pack option menu element "reflectionCaptureEnabled" defined in shaders.properties
[17:55:58] [Render thread/WARN]: Unable to resolve shader pack option menu element "subsurfaceScatteringEnabled" defined in shaders.properties
[17:55:58] [Render thread/WARN]: Unable to resolve shader pack option menu element "CONFIDENCE" defined in shaders.properties
[17:55:58] [Render thread/INFO]: Profile: Default (+0 options changed by user)
[17:55:59] [Render thread/INFO]: Using shaderpack: UShader_v2.0.zip
[17:55:59] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[17:55:59] [Render thread/WARN]: Shader compilation log for prepare.fsh: 0(64) : error C7599: (location = 0, component = 0) already used

[17:55:59] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: Shader compilation failed!
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:237) ~[oculus-mc1.19.2-1.2.8a.jar%23147!/:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:94) ~[oculus-mc1.19.2-1.2.8a.jar%23147!/:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:215) ~[oculus-mc1.19.2-1.2.8a.jar%23147!/:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:641) ~[oculus-mc1.19.2-1.2.8a.jar%23147!/:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[oculus-mc1.19.2-1.2.8a.jar%23147!/:?]
	at net.coderbot.iris.Iris.reload(Iris.java:583) ~[oculus-mc1.19.2-1.2.8a.jar%23147!/:?]
	at net.coderbot.iris.apiimpl.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:28) ~[oculus-mc1.19.2-1.2.8a.jar%23147!/:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:468) ~[oculus-mc1.19.2-1.2.8a.jar%23147!/:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$1(ShaderPackScreen.java:195) ~[oculus-mc1.19.2-1.2.8a.jar%23147!/:?]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:110) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:204) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23149!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.4.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.RuntimeException: Failed to compile FRAGMENT shader for program prepare.fsh
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:78) ~[oculus-mc1.19.2-1.2.8a.jar%23147!/:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[oculus-mc1.19.2-1.2.8a.jar%23147!/:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:233) ~[oculus-mc1.19.2-1.2.8a.jar%23147!/:?]
	... 40 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:40) ~[oculus-mc1.19.2-1.2.8a.jar%23147!/:?]
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:21) ~[oculus-mc1.19.2-1.2.8a.jar%23147!/:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:76) ~[oculus-mc1.19.2-1.2.8a.jar%23147!/:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[oculus-mc1.19.2-1.2.8a.jar%23147!/:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:233) ~[oculus-mc1.19.2-1.2.8a.jar%23147!/:?]
	... 40 more
[17:55:59] [Render thread/INFO]: Stopping worker threads
[17:55:59] [Render thread/INFO]: Started 6 worker threads
```

### Minecraft Version

1.19.2

### Oculus Version

1.2.8a

### Rubidium Version

0.6.2

### Operating System

W10

### What is your GPU?

1070Ti

### Java Version

17

**Comment by shal0l** [comment]
Nevermind, it appears this just won't be patched
https://github.com/Asek3/Oculus/issues/172
