### ISSUE TITLE
Oculus Shaders broken on StoneBlock 3

### ISSUE THREAD

**Issue by Syncinus** [Asek3/Oculus#295]
### What happened?

On Stoneblock 3 loading any shaders breaks rendering. Tested with SEUS Renewed, BSL, Complementary Reimagined, Voxels Rethinking, and Soft Voxels. They all break the GUI leaving only text and some icons (particularily item icons) still rendering, with text rendering having occasional issues. World rendering is always completely broken, but in different ways depending on the shader: sometimes it is extremely dim and blurry (Rethinking Voxels), other times nothing but the skybox renders (SEUS Renewed).

### Screenshots

SEUS Renewed (I should be looking at a sea lantern)
![image](https://user-images.githubusercontent.com/34169172/217478113-0d4f0950-ab55-4e12-abbf-78095ebd1dc1.png)
Rethinking Voxels
![image](https://user-images.githubusercontent.com/34169172/217478426-90e8dc8b-14be-4daa-afb9-5c060e52624c.png)

### Minecraft Version

Minecraft 1.18.2, StoneBlock 3 1.6.1

### Oculus Version

oculus-1.4.3a

### Rubidium Version

rubidium-0.5.4

### Operating System

Windows 11 Insider Edition - Dev Channel

### What is your GPU?

Gigabyte GeForce RTX 4090

### Java Version

Java 17

### Additional context

[debug.log](https://github.com/Asek3/Oculus/files/10683532/debug.log)

**Comment by Nyxlanders** [comment]
Yeah, same is happening to me, any fix yet?

**Comment by IIWolfieII** [comment]
Same here.
Happening on Stoneblock 3 1.8.0 as well.

**Comment by starryfae** [comment]
Try removing Literal Sky Block and see if that fixes the issue.

https://www.curseforge.com/minecraft/mc-mods/literal-sky-block

**Comment by GnomeBeans** [comment]
Hope this could help crack it. It seems pretty consistent once I disabled Literal Sky Block with just about any shader.

`[26Aug2024 21:40:29.935] [Render thread/INFO] [Oculus/]: Using shaderpack: BSLOriginal_v8.3.zip
[26Aug2024 21:40:29.935] [Render thread/INFO] [Oculus/]: Creating pipeline for dimension OVERWORLD
[26Aug2024 21:40:30.008] [Render thread/INFO] [Oculus/]: Starting custom uniform resolving
[26Aug2024 21:40:30.048] [Render thread/WARN] [Oculus/]: Failed to resolve uniform isSwamp, reason: Unknown variable: BIOME_MANGROVE_SWAMP ( = FunctionCall{smooth {[Number{4}, FunctionCall{if {[FunctionCall{in {[Id{biome}, Id{BIOME_SWAMP}, Id{BIOME_MANGROVE_SWAMP}]} }, Number{1}, Number{0}]} }, Number{10}, Number{10}]} })
java.lang.RuntimeException: Unknown variable: BIOME_MANGROVE_SWAMP
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpressionInternal(ExpressionResolver.java:219) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpressionInternal(ExpressionResolver.java:73) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpression(ExpressionResolver.java:133) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpressionInternal(ExpressionResolver.java:190) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpressionInternal(ExpressionResolver.java:73) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpression(ExpressionResolver.java:133) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpression(ExpressionResolver.java:120) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpressionInternal(ExpressionResolver.java:190) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpressionInternal(ExpressionResolver.java:73) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveCallExpression(ExpressionResolver.java:133) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpressionInternal(ExpressionResolver.java:190) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at kroppeb.stareval.resolver.ExpressionResolver.resolveExpression(ExpressionResolver.java:42) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms.<init>(CustomUniforms.java:53) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:317) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at net.coderbot.iris.uniforms.custom.CustomUniforms$Builder.build(CustomUniforms.java:329) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:252) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:664) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at net.coderbot.iris.Iris.reload(Iris.java:606) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at net.coderbot.iris.apiimpl.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:28) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:537) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$2(ShaderPackScreen.java:222) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:40) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%230!/:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%235!/:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar%230!/:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:333) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1068) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23276!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.14.jar%2352!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-prism-2024-02-29.jar:prism-2024-02-29]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
[26Aug2024 21:40:30.608] [Render thread/WARN] [Oculus/]: [Patcher] gl_FragColor is not supported yet, please use gl_FragData! Assuming that the shaderpack author intended to use gl_FragData[0]...
[26Aug2024 21:40:31.819] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads`
