### ISSUE TITLE
Crash trying to run in server dist

### ISSUE THREAD

**Issue by SrRapero720** [Asek3/Oculus#347]
### Minecraft Version

1.18.2

### Oculus Version

oculus-1.5.2.jar

### Sodium Version

rubidium-0.5.5.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GT 1030

### Java Version

Java 17.0.5+1

### Reproduction Steps

1. Run a server with oculus

### Crash Report file and latest.log

```shell
[23:29:57] [main/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 31065dfc-e1cd-4439-b71c-817480ab376a
---- Minecraft Crash Report ----
// My bad.

Time: 17/04/23 23:29
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.2.0_mapped_parchment_2022.08.07-1.18.2-recomp.jar%2378%2385!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.18.2-40.2.0_mapped_parchment_2022.08.07-1.18.2-recomp.jar%2378%2385!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:112) ~[forge-1.18.2-40.2.0_mapped_parchment_2022.08.07-1.18.2-recomp.jar%2379!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.ForgeServerUserdevLaunchHandler.lambda$launchService$0(ForgeServerUserdevLaunchHandler.java:21) ~[fmlloader-1.18.2-40.2.0.jar%230!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.18.2-40.2.0.jar%230!/:1.0] {}
[WATERCoRE] Mixins in Stacktrace: None found
-- MOD oculus --
Details:
	Mod File: /C:/Users/SrRap/.gradle/caches/forge_gradle/deobf_dependencies/curse/maven/oculus-581495/4451905_mapped_parchment_2022.08.07-1.18.2/oculus-581495-4451905_mapped_parchment_2022.08.07-1.18.2.jar
	Failure message: Oculus (oculus) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
	Mod Version: 1.5.2
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.18.2-40.2.0.jar:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {}
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?] {}
	at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?] {}
	at java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.0.jar%2380!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.0.jar%2383!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

[WATERCoRE] Mixins in Stacktrace: None found

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.5, JetBrains s.r.o.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), JetBrains s.r.o.
	Memory: 211210752 bytes (201 MiB) / 440401920 bytes (420 MiB) up to 4282384384 bytes (4084 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GT 1030
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1d01
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3141
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 33909.00
	Virtual memory used (MB): 27713.86
	Swap memory total (MB): 17576.94
	Swap memory used (MB): 2933.66
	JVM Flags: 0 total; 
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeserveruserdev
	ModLauncher naming: mcp
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		forge-1.18.2-40.2.0_mapped_parchment_2022.08.07-1.|Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		fastload-630620-4271605_mapped_parchment_2022.08.0|Fastload                      |fastload                      |2.6.9+1.18.2        |COMMON_SET|Manifest: NOSIGNATURE
		fancyvideo-api-591686-3803736_mapped_parchment_202|FancyVideo API                |fancyvideo_api                |1.1.0.0             |COMMON_SET|Manifest: NOSIGNATURE
		video-player-645407-4348349_mapped_parchment_2022.|VideoPlayer                   |videoplayer                   |0.5                 |COMMON_SET|Manifest: NOSIGNATURE
		spark-361579-3824951_mapped_parchment_2022.08.07-1|spark                         |spark                         |1.9.11              |COMMON_SET|Manifest: NOSIGNATURE
		WATERCoRE-1.4.0-DEV20.jar                         |WATERCoRE                     |watercore                     |1.4.0-DEV20         |COMMON_SET|Manifest: NOSIGNATURE
		                                                  |Forge                         |forge                         |40.2.0              |COMMON_SET|Manifest: NOSIGNATURE
		rubidium-574856-4451888_mapped_parchment_2022.08.0|Rubidium                      |rubidium                      |0.5.5               |COMMON_SET|Manifest: NOSIGNATURE
		lazy-dfu-forge-460819-3544496_mapped_parchment_202|LazyDFU                       |lazydfu                       |0.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		main                                              |WATERFrAMES                   |waterframes                   |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		oculus-581495-4451905_mapped_parchment_2022.08.07-|Oculus                        |oculus                        |1.5.2               |ERROR     |Manifest: NOSIGNATURE
		creativecore-257814-4394989_mapped_parchment_2022.|CreativeCore                  |creativecore                  |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		ferritecore-429235-4074294_mapped_parchment_2022.0|Ferrite Core                  |ferritecore                   |4.2.2               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 31065dfc-e1cd-4439-b71c-817480ab376a
	FML: 40.2
	Forge: net.minecraftforge:40.2.0[23:29:57] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Oculus (oculus) has failed to load correctly
§7java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
]
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:222) ~[fmlcore-1.18.2-40.2.0.jar%2383!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.0.jar%2383!/:?] {}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.0.jar%2383!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:164) ~[fmlcore-1.18.2-40.2.0.jar%2383!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:164) ~[fmlcore-1.18.2-40.2.0.jar%2383!/:?] {}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.18.2-40.2.0_mapped_parchment_2022.08.07-1.18.2-recomp.jar%2378%2385!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:112) ~[forge-1.18.2-40.2.0_mapped_parchment_2022.08.07-1.18.2-recomp.jar%2379!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.ForgeServerUserdevLaunchHandler.lambda$launchService$0(ForgeServerUserdevLaunchHandler.java:21) ~[fmlloader-1.18.2-40.2.0.jar%230!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2311!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

Process finished with exit code 0
```

### Additional context

Yes, is useless try to run oculus in a server. but in dev enviroment is necesary, because curretly if i need to run a server and a client demo, i have to first run client, second remove oculus in gradle, sync and run server (and sometimes that no works)

**Comment by sandalle** [comment]
Duplicate of https://github.com/Asek3/Oculus/issues/86 .

**Comment by SrRapero720** [comment]
Duplicated or not, both are not answered
