### ISSUE TITLE
"$$13" is null

### ISSUE THREAD

**Issue by OMG67** [Asek3/Oculus#368]
### Minecraft Version

1.18.2

### Oculus Version

oculus-1.5.2.jar

### Sodium Version

 rubidium-0.5.6.jar

### Operating System

W10

### What is your GPU?

Nividia RTX 3060Ti

### Java Version

Java 17.0.1, Microsoft

### Reproduction Steps

1. Enter a game with ComplementaryShaders on, extreme quality.
2. Play for a while
3. Depending on a factor I don't know, sometimes it crashed 5 seconds into the game, sometimes it doesn't crash for days. Last time it crashed was while I flew using elytras.

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Why did you do that?

Time: 5/20/23, 2:38 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.ShaderInstance.m_173350_(String, Object)" because "$$13" is null
	at com.mojang.blaze3d.vertex.BufferUploader.m_166838_(BufferUploader.java:100) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at com.mojang.blaze3d.vertex.BufferUploader.m_85761_(BufferUploader.java:52) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.coderbot.batchedentityrendering.impl.BufferSegmentRenderer.drawInner(BufferSegmentRenderer.java:29) ~[oculus-1.5.2.jar%2367!/:?] {re:classloading}
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.m_109911_(FullyBufferedMultiBufferSource.java:118) ~[oculus-1.5.2.jar%2367!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.handler$zhl000$batchedentityrendering$beginTranslucents(LevelRenderer.java:4091) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1359) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1061) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:835) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.2.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.vertex.BufferUploader.m_166838_(BufferUploader.java:100) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at com.mojang.blaze3d.vertex.BufferUploader.m_85761_(BufferUploader.java:52) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.coderbot.batchedentityrendering.impl.BufferSegmentRenderer.drawInner(BufferSegmentRenderer.java:29) ~[oculus-1.5.2.jar%2367!/:?] {re:classloading}
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.m_109911_(FullyBufferedMultiBufferSource.java:118) ~[oculus-1.5.2.jar%2367!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.handler$zhl000$batchedentityrendering$beginTranslucents(LevelRenderer.java:4091) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1359) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1061) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['MongolowGamer69'/85, l='ClientLevel', x=-107.98, y=184.54, z=-577.63]]
	Chunk stats: 1024, 614
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,140,27), Section: (at 0,12,11 in 1,8,1; chunk contains blocks 16,-64,16 to 31,959,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,959,511)
	Level time: 15635 game time, 15635 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,pl:mixin:APP:dynamiclightsreforged.mixins.json:ClientWorldMixin,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2264) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:687) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2380!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.2.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources, Stay_True_1.18.zip, Xaero's Minimap - Mod Icons.zip, Tissou's Zombie Pack 1.18_2.6.zip, Unity-1.18.X-Dark-0.9.1.zip, [1.2] Enhanced Boss Bars.zip, bowcharginganimation.zip

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 995684864 bytes (949 MiB) / 2808086528 bytes (2678 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2489
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.93
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.93
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.93
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.93
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37519.71
	Virtual memory used (MB): 24055.15
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 13.38
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Loaded Shaderpack: ComplementaryShaders_v4.3.3.zip
		Profile: EXTREME (+3 options changed by user)
	Launched Version: forge-40.2.2
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.79, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, file/Stay_True_1.18.zip, file/Xaero's Minimap - Mod Icons.zip, file/Tissou's Zombie Pack 1.18_2.6.zip, file/Unity-1.18.X-Dark-0.9.1.zip, file/[1.2] Enhanced Boss Bars.zip, file/bowcharginganimation.zip (incompatible)
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['MongolowGamer69'/85, l='ServerLevel[New World]', x=-107.98, y=184.54, z=-577.63]]
	Data Packs: vanilla, mod:dynamiclightsreforged (incompatible), mod:enchdesc (incompatible), mod:do_a_barrel_roll (incompatible), mod:transparent (incompatible), mod:jei (incompatible), mod:torohealth (incompatible), mod:paintings (incompatible), mod:sophisticatedcore (incompatible), mod:rubidium (incompatible), mod:xaerominimap, mod:terraforged, mod:xaeroworldmap, mod:configured (incompatible), mod:inventoryhud (incompatible), mod:bookshelf, mod:sophisticatedbackpacks (incompatible), mod:architectury (incompatible), mod:terralith, mod:rubidium_extras (incompatible), mod:cloth_config (incompatible), mod:sound_physics_remastered (incompatible), mod:forge, mod:appleskin (incompatible), mod:cobblefordays (incompatible), mod:dynamictrees (incompatible), mod:dynamictreesplus (incompatible), mod:dsurround, file/TerraForged.zip, mod:oculus (incompatible)
	World Generation: Stable
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		dynamiclightsreforged-1.18.2_v1.3.3.jar           |Rubidium Dynamic Lights       |dynamiclightsreforged         |1.18.2_v1.3.3       |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.18.2-10.0.12.jar  |EnchantmentDescriptions       |enchdesc                      |10.0.12             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		do-a-barrel-roll-2.5.3+1.18.2-forge.jar           |Do A Barrel Roll              |do_a_barrel_roll              |2.5.3+1.18.2        |DONE      |Manifest: NOSIGNATURE
		transparent-4.1.0+1.18.2-forge.jar                |Transparent                   |transparent                   |4.1.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.7.1.255.jar                          |Just Enough Items             |jei                           |9.7.1.255           |DONE      |Manifest: NOSIGNATURE
		torohealth-1.18-forge-2.jar                       |ToroHealth                    |torohealth                    |1.18-forge-2        |DONE      |Manifest: NOSIGNATURE
		Paintings-forge-1.18.2-9.1.2.1.jar                |Paintings ++                  |paintings                     |9.1.2.1             |DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.18.2-0.5.53.260.jar           |Sophisticated Core            |sophisticatedcore             |1.18.2-0.5.53.260   |DONE      |Manifest: NOSIGNATURE
		rubidium-0.5.6.jar                                |Rubidium                      |rubidium                      |0.5.6               |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_23.4.3_Forge_1.18.2.jar            |Xaero's Minimap               |xaerominimap                  |23.4.3              |DONE      |Manifest: NOSIGNATURE
		oculus-1.5.2.jar                                  |Oculus                        |oculus                        |1.5.2               |DONE      |Manifest: NOSIGNATURE
		TerraForged-1.18.2-0.3.1-alpha-2.jar              |TerraForged                   |terraforged                   |0.3.1               |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.30.2_Forge_1.18.2.jar            |Xaero's World Map             |xaeroworldmap                 |1.30.2              |DONE      |Manifest: NOSIGNATURE
		configured-2.0.1-1.18.2.jar                       |Configured                    |configured                    |2.0.1               |DONE      |Manifest: NOSIGNATURE
		invhud.forge.1.18.2-3.4.12.jar                    |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.12              |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.18.2-13.2.53.jar                |Bookshelf                     |bookshelf                     |13.2.53             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.18.2-3.18.46.821.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.2-3.18.46.821  |DONE      |Manifest: NOSIGNATURE
		architectury-4.11.93-forge.jar                    |Architectury                  |architectury                  |4.11.93             |DONE      |Manifest: NOSIGNATURE
		Terralith_v2.2.3.jar                              |Terralith                     |terralith                     |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		rubidium_extras-1.18.2_v1.3.2.jar                 |Rubidium Extras               |rubidium_extras               |1.18.2_v1.3.2       |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.4.90-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.4.90              |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.18.2-1.0.6.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.18.2-1.0.6        |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.2.2-universal.jar                 |Forge                         |forge                         |40.2.2              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.18.2-2.4.1.jar                |AppleSkin                     |appleskin                     |2.4.1+mc1.18.2      |DONE      |Manifest: NOSIGNATURE
		CobbleForDays-1.5.1.jar                           |Cobble For Days               |cobblefordays                 |1.5.1               |DONE      |Manifest: NOSIGNATURE
		DynamicTrees-1.18.2-1.0.2.jar                     |Dynamic Trees                 |dynamictrees                  |1.18.2-1.0.2        |DONE      |Manifest: NOSIGNATURE
		DynamicTreesPlus-1.18.2-1.0.0.jar                 |Dynamic Trees Plus            |dynamictreesplus              |1.18.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
		DynamicSurroundings-5.0.0.4.jar                   |§3Dynamic Surroundings: Resurr|dsurround                     |5.0.0.4             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 2124a4b2-a2ff-4db2-8cd7-ff5629cfe32c
	FML: 40.2
	Forge: net.minecraftforge:40.2.2
```

### Additional context

I know that some shaders are incompatible, maybe these are but I don't think so since they usually work with no problems, if that's the cause is there a way to make them compatible? The compatibility mode maybe?

**Comment by henrymwebb** [comment]
It has nothing to do with the shaders. This bug occurs for me even with shaders disabled.
