### ISSUE TITLE
[1.18.2] Falling Sand not rendering

### ISSUE THREAD

**Issue by OverEarth12** [Asek3/Oculus#39]
### What happened?

Falling Sand will not render when installed this mod. I tried this with Rubidium alone, it's render again

### Screenshots

Youtube Video:
https://www.youtube.com/watch?v=aXIsP9egTC4
![2022-04-07_22 16 07](https://user-images.githubusercontent.com/56574543/162234694-cc3f9e89-ea3c-4886-8a1a-db6536c3a763.png)

### Relevant log output

```shell
[21:58:03] [main/INFO]: ModLauncher running: args [--username, OverEarth, --version, forge-40.0.41, --gameDir, C:\curseforge\minecraft\Instances\Test2, --assetsDir, C:\curseforge\minecraft\Install\assets, --assetIndex, 1.18, --uuid, 51e868f0f425470496ff16a650b5a918, --accessToken, ????????, --clientId, NjhjNTExZmItNzU2Ny00MGIyLWIyNWMtM2ZjYWY0MTQyYWM5, --xuid, 2535438585770384, --userType, msa, --versionType, release, --width, 854, --height, 480, --launchTarget, forgeclient, --fml.forgeVersion, 40.0.41, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[21:58:03] [main/INFO]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
[21:58:03] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
[21:58:03] [main/INFO]: Found mod file oculus-mc1.18.2-1.2.2a.jar of type MOD with locator {mods folder locator at C:\curseforge\minecraft\Instances\Test2\mods}
[21:58:03] [main/INFO]: Found mod file rubidium-0.5.1a.jar of type MOD with locator {mods folder locator at C:\curseforge\minecraft\Instances\Test2\mods}
[21:58:03] [main/INFO]: Found mod file fmlcore-1.18.2-40.0.41.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@88d6f9b
[21:58:03] [main/INFO]: Found mod file javafmllanguage-1.18.2-40.0.41.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@88d6f9b
[21:58:03] [main/INFO]: Found mod file mclanguage-1.18.2-40.0.41.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@88d6f9b
[21:58:03] [main/INFO]: Found mod file client-1.18.2-20220404.173914-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@88d6f9b
[21:58:03] [main/INFO]: Found mod file forge-1.18.2-40.0.41-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@88d6f9b
[21:58:05] [main/ERROR]: Mixin config mixins.oculus.compat.sodium.json does not specify "minVersion" property
[21:58:05] [main/INFO]: Compatibility level set to JAVA_17
[21:58:05] [main/ERROR]: Mixin config rubidium.mixins.json does not specify "minVersion" property
[21:58:05] [main/INFO]: Launching target 'forgeclient' with arguments [--version, forge-40.0.41, --gameDir, C:\curseforge\minecraft\Instances\Test2, --assetsDir, C:\curseforge\minecraft\Install\assets, --uuid, 51e868f0f425470496ff16a650b5a918, --username, OverEarth, --assetIndex, 1.18, --accessToken, ????????, --clientId, NjhjNTExZmItNzU2Ny00MGIyLWIyNWMtM2ZjYWY0MTQyYWM5, --xuid, 2535438585770384, --userType, msa, --versionType, release, --width, 854, --height, 480]
[21:58:05] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[21:58:05] [main/INFO]: Loaded configuration file for Rubidium: 29 options available, 0 override(s) found
[21:58:16] [Render thread/WARN]: Method overwrite conflict for m_85995_ in rubidium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[21:58:19] [Render thread/WARN]: Assets URL 'union:/C:/curseforge/minecraft/Install/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-srg.jar%2354!/assets/.mcassetsroot' uses unexpected schema
[21:58:19] [Render thread/WARN]: Assets URL 'union:/C:/curseforge/minecraft/Install/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-srg.jar%2354!/data/.mcassetsroot' uses unexpected schema
[21:58:19] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[21:58:20] [Render thread/INFO]: Setting user: OverEarth
[21:58:20] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
[21:58:23] [modloading-worker-0/INFO]: Forge mod loading, version 40.0.41, for MC 1.18.2 with MCP 20220404.173914
[21:58:23] [modloading-worker-0/INFO]: MinecraftForge v40.0.41 Initialized
[21:58:27] [Render thread/WARN]: Hardware information:
[21:58:27] [Render thread/WARN]: CPU: 8x Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
[21:58:27] [Render thread/WARN]: GPU: NVIDIA GeForce GTX 1050/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 511.79)
[21:58:27] [Render thread/WARN]: OS: Windows 10 (10.0)
[21:58:29] [Render thread/WARN]: Method overwrite conflict for getNativeMemoryUsage in rubidium.mixins.json:features.debug.MixinDebugHud, previously written by net.coderbot.iris.mixin.MixinDebugScreenOverlay. Skipping method.
[21:58:29] [Render thread/INFO]: Narrator library for x64 successfully loaded
[21:58:29] [Render thread/INFO]: Reloading ResourceManager: Default, Mod Resources
[21:58:30] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[21:58:31] [Forge Version Check/INFO]: [forge] Found status: BETA Current: 40.0.41 Target: 40.0.41
[21:58:44] [Thread-7/ERROR]: An error occurred building event handler
java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because the return value of "java.lang.Thread.getContextClassLoader()" is null
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-5.0.3.jar:5.0.3+70+master.d7d405b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) [securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) [securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) [securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
[21:58:44] [Thread-7/ERROR]: An error occurred building event handler
java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because the return value of "java.lang.Thread.getContextClassLoader()" is null
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-5.0.3.jar:5.0.3+70+master.d7d405b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) [securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) [securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) [securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
[21:58:44] [Thread-7/ERROR]: An error occurred building event handler
java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because the return value of "java.lang.Thread.getContextClassLoader()" is null
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-5.0.3.jar:5.0.3+70+master.d7d405b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) [securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) [securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) [securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.minecraftforge.client.gui.ModListScreen.<init>(ModListScreen.java:99) [forge-1.18.2-40.0.41-universal.jar%2358!/:?]
[21:58:44] [Thread-7/ERROR]: An error occurred building event handler
java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because the return value of "java.lang.Thread.getContextClassLoader()" is null
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-5.0.3.jar:5.0.3+70+master.d7d405b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) [securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) [securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) [securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.minecraftforge.client.gui.ModListScreen.<init>(ModListScreen.java:99) [forge-1.18.2-40.0.41-universal.jar%2358!/:?]
[21:58:44] [Thread-7/ERROR]: An error occurred building event handler
java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because the return value of "java.lang.Thread.getContextClassLoader()" is null
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-5.0.3.jar:5.0.3+70+master.d7d405b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) [securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) [securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) [securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.minecraftforge.client.gui.ModListScreen.<init>(ModListScreen.java:99) [forge-1.18.2-40.0.41-universal.jar%2358!/:?]
[21:58:54] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (Realtek(R) Audio)
[21:58:54] [Render thread/INFO]: Sound engine started
[21:58:54] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[21:58:54] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[21:58:54] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[21:58:54] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[21:58:54] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[21:58:54] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[21:58:54] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[21:58:56] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[21:58:56] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[21:58:56] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[21:59:02] [Render thread/INFO]: Injecting existing registry data into this CLIENT instance
[21:59:05] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:59:05] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:59:05] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[21:59:05] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[21:59:05] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:59:12] [Render thread/INFO]: Loaded 7 recipes
[21:59:15] [Render thread/INFO]: Loaded 1141 advancements
[21:59:16] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[21:59:16] [Server thread/INFO]: Starting integrated minecraft server version 1.18.2
[21:59:16] [Server thread/INFO]: Generating keypair
[21:59:16] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[21:59:18] [Render thread/INFO]: Preparing spawn area: 0%
[21:59:18] [Render thread/INFO]: Preparing spawn area: 0%
[21:59:18] [Render thread/INFO]: Preparing spawn area: 0%
[21:59:18] [Render thread/INFO]: Preparing spawn area: 0%
[21:59:18] [Render thread/INFO]: Preparing spawn area: 0%
[21:59:19] [Render thread/INFO]: Preparing spawn area: 0%
[21:59:20] [Render thread/INFO]: Preparing spawn area: 0%
[21:59:20] [Render thread/INFO]: Preparing spawn area: 0%
[21:59:20] [Render thread/INFO]: Preparing spawn area: 0%
[21:59:21] [Render thread/INFO]: Preparing spawn area: 0%
[21:59:21] [Render thread/INFO]: Preparing spawn area: 0%
[21:59:22] [Render thread/INFO]: Preparing spawn area: 1%
[21:59:22] [Render thread/INFO]: Preparing spawn area: 7%
[21:59:23] [Render thread/INFO]: Preparing spawn area: 8%
[21:59:23] [Render thread/INFO]: Preparing spawn area: 10%
[21:59:24] [Render thread/INFO]: Preparing spawn area: 29%
[21:59:24] [Render thread/INFO]: Preparing spawn area: 38%
[21:59:25] [Render thread/INFO]: Preparing spawn area: 80%
[21:59:26] [Server thread/INFO]: Successfully initialized permission handler forge:default_handler
[21:59:26] [Render thread/INFO]: Time elapsed: 9640 ms
[21:59:26] [Server thread/INFO]: Changing view distance to 12, from 10
[21:59:26] [Server thread/INFO]: Changing simulation distance to 12, from 0
[21:59:29] [Netty Local Client IO #0/INFO]: Connected to a modded server.
[21:59:29] [Server thread/INFO]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@736a5695
[21:59:29] [Server thread/INFO]: OverEarth[local:E:330971f5] logged in with entity id 240 at (47.03322584921679, 66.62143534848114, 113.10620543943206)
[21:59:30] [Server thread/INFO]: OverEarth joined the game
[21:59:30] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2115ms or 42 ticks behind
[21:59:33] [Render thread/INFO]: Started 2 worker threads
[21:59:34] [Render thread/INFO]: Loaded 21 advancements
[21:59:34] [Render thread/WARN]: Creating pipeline for dimension OVERWORLD
[21:59:37] [Server thread/INFO]: Saving and pausing game...
[21:59:37] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[21:59:42] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[21:59:42] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[21:59:49] [Server thread/INFO]: Saving and pausing game...
[21:59:49] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[21:59:49] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[21:59:49] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[21:59:56] [Server thread/INFO]: Saving and pausing game...
[21:59:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[21:59:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[21:59:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[22:00:10] [Server thread/INFO]: Saving and pausing game...
[22:00:10] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[22:00:10] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[22:00:10] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[22:00:56] [Server thread/INFO]: Saving and pausing game...
[22:00:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[22:00:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[22:00:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[22:01:47] [Render thread/INFO]: Loaded 24 advancements
[22:02:06] [Server thread/INFO]: Saving and pausing game...
[22:02:06] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[22:02:06] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[22:02:06] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[22:07:03] [Server thread/INFO]: OverEarth lost connection: Disconnected
[22:07:03] [Server thread/INFO]: OverEarth left the game
[22:07:03] [Server thread/INFO]: Stopping singleplayer server as player logged out
[22:07:03] [Server thread/INFO]: Stopping server
[22:07:03] [Server thread/INFO]: Saving players
[22:07:03] [Server thread/INFO]: Saving worlds
[22:07:05] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[22:07:05] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[22:07:05] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[22:07:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[22:07:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[22:07:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[22:07:06] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[22:07:06] [Render thread/INFO]: Stopping worker threads
[22:07:07] [Render thread/INFO]: Stopping!
```

### Minecraft Version

Minecraft 1.18.2

### Iris Version

oculus-mc1.18.2-1.2.2a

### Sodium Version

rubidium-0.5.1a

### Operating System

Windows 10

### What is your GPU?

nvidia geforce gtx 1050

### Java Version

Java 17

**Comment by Asek3** [comment]
Probably resolved in 1.2.4. Also plz update Rubidium
