### ISSUE TITLE
Crash loading/rendering world in 1.20.1

### ISSUE THREAD

**Issue by olivezinha** [Asek3/Oculus#397]
### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20-1.6.4

### Sodium Version

rubidium-0.6.5

### Operating System

Windows 11

### What is your GPU?

Rtx 2060

### Java Version

Java 8

### Reproduction Steps

1. I reacherd a village
2. Game Crashed
3. I can't enter the world again because just crash

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-06-28 22:44:09
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.RenderType.m_110185_()" because "type" is null
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.m_109911_(FullyBufferedMultiBufferSource.java:136) ~[oculus-mc1.20-1.6.4.jar%23266!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1377) ~[client-1.20.1-20230612.114412-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:weeping_angels-common.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_FixKeybindUnpressedInEmoteWheel,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:feature.emote.Mixin_AllowMovementDuringEmoteWheel_HandleKeybinds,pl:mixin:APP:mixins.essential.json:feature.skin_overwrites.Mixin_InstallTrustingServicesKeyInfo,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:weeping_angels-common.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_FixKeybindUnpressedInEmoteWheel,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:feature.emote.Mixin_AllowMovementDuringEmoteWheel_HandleKeybinds,pl:mixin:APP:mixins.essential.json:feature.skin_overwrites.Mixin_InstallTrustingServicesKeyInfo,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.0.34.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.0.34.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.0.34.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.0.34.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.coderbot.batchedentityrendering.impl.FullyBufferedMultiBufferSource.m_109911_(FullyBufferedMultiBufferSource.java:136) ~[oculus-mc1.20-1.6.4.jar%23266!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1377) ~[client-1.20.1-20230612.114412-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['olivezinha'/59, l='ClientLevel', x=-517.27, y=106.00, z=945.28]]
	Chunk stats: 1024, 505
	Level dimension: minecraft:overworld
	Level spawn location: World: (-48,85,112), Section: (at 0,5,0 in -3,5,7; chunk contains blocks -48,-64,112 to -33,319,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 141329 game time, 169014 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:455) ~[client-1.20.1-20230612.114412-srg.jar%23294!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:APP:mixins.essential.json:feature.particles.Mixin_AddParticleSystemToClientWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:weeping_angels-common.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_FixKeybindUnpressedInEmoteWheel,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:feature.emote.Mixin_AllowMovementDuringEmoteWheel_HandleKeybinds,pl:mixin:APP:mixins.essential.json:feature.skin_overwrites.Mixin_InstallTrustingServicesKeyInfo,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:combatroll.mixins.json:MinecraftClientMixin,pl:mixin:APP:weeping_angels-common.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_FixKeybindUnpressedInEmoteWheel,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:feature.emote.Mixin_AllowMovementDuringEmoteWheel_HandleKeybinds,pl:mixin:APP:mixins.essential.json:feature.skin_overwrites.Mixin_InstallTrustingServicesKeyInfo,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.0.34.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.0.34.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.0.34.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.0.34.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources, file/EBE_1.20.x_v1.1.zip, file/[1.3] Enhanced Boss Bars.zip, file/Pixel+Perfection+Legacy+13.20.1.zip, file/Default-Dark-Mode-1.20-2023.6.0.zip, essential

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1836177752 bytes (1751 MiB) / 3422552064 bytes (3264 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600G with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f08
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3623
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 26930.59
	Virtual memory used (MB): 20852.30
	Swap memory total (MB): 10752.00
	Swap memory used (MB): 605.73
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: 1.20.1-forge-47.0.34
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.23, NVIDIA Corporation
	Window size: 1920x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, file/EBE_1.20.x_v1.1.zip, file/[1.3] Enhanced Boss Bars.zip, file/Pixel+Perfection+Legacy+13.20.1.zip, file/Default-Dark-Mode-1.20-2023.6.0.zip
	Current Language: pt_br
	CPU: 12x AMD Ryzen 5 5600G with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['olivezinha'/59, l='ServerLevel[Chameguinho]', x=-517.27, y=106.00, z=945.28]]
	Data Packs: vanilla, mod:doubledoors, mod:mr_rpg_origins, mod:supermartijn642configlib (incompatible), mod:trashslot, mod:zombiehorsespawn, mod:watermedia (incompatible), mod:harvestwithease, mod:weeping_angels (incompatible), mod:spawn_animations_mr, mod:playeranimator (incompatible), mod:jei, mod:visualworkbench, mod:horseexpert, mod:realisticbees, mod:more_mobs_mr, mod:journeymap (incompatible), mod:badpackets (incompatible), mod:cpm (incompatible), mod:mixinextras (incompatible), mod:kambrik (incompatible), mod:midnightlib (incompatible), mod:cryingghasts, mod:skeletonhorsespawn, mod:additionalstructures, mod:resourcify (incompatible), mod:balm, mod:vanillazoom, mod:cat_jam (incompatible), mod:dungeons_andtaverns_mr, mod:cloth_config (incompatible), mod:sound_physics_remastered, mod:skinlayers3d, mod:forge, mod:stackrefill, mod:ctov, mod:durabilitytooltip (incompatible), mod:emotecraft (incompatible), mod:corpse, mod:dungeons_arise (incompatible), mod:mob_captains_mr (incompatible), mod:handcrafted (incompatible), mod:combatroll (incompatible), mod:creativecore, mod:resourcefulconfig (incompatible), mod:servercore (incompatible), mod:wthit (incompatible), mod:bountiful (incompatible), mod:kotlinforforge (incompatible), mod:notenoughanimations, mod:curios (incompatible), mod:collective, mod:camera, mod:resourcefullib (incompatible), mod:bettertridents, mod:pmmo, mod:appleskin (incompatible), mod:puzzleslib, mod:corgilib, mod:followersteleporttoo, mod:waterframes (incompatible), mod:playerrevive, mod:healingcampfire, mod:essential (incompatible), mod:rubidium, mod:oculus, mod:waystones, mod:enhancedcelestials (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.0.34.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.0.34.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.0.34.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.0.34.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.0.34.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar essential-loader TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@4.3.0
		lowcodefml@null
	Mod List: 
		doubledoors-1.20.1-5.0.jar                        |Double Doors                  |doubledoors                   |5.0                 |DONE      |Manifest: NOSIGNATURE
		rpg-origins-1.3.3.jar                             |RPG Origins                   |mr_rpg_origins                |1.3.3               |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.6-forge-mc1.20.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.6               |DONE      |Manifest: NOSIGNATURE
		trashslot-forge-1.20-15.0.0.jar                   |TrashSlot                     |trashslot                     |15.0.0              |DONE      |Manifest: NOSIGNATURE
		zombiehorsespawn-1.20.1-4.6.jar                   |Zombie Horse Spawn            |zombiehorsespawn              |4.6                 |DONE      |Manifest: NOSIGNATURE
		watermedia-1.2.16.jar                             |WaterMedia                    |watermedia                    |1.2.16              |DONE      |Manifest: NOSIGNATURE
		harvestwithease-1.20.1-7.0.0.1-forge.jar          |Harvest with ease             |harvestwithease               |7.0.0.1             |DONE      |Manifest: NOSIGNATURE
		Weeping-Angels-46.0.1-forge.jar                   |Weeping Angels                |weeping_angels                |46.0.1              |DONE      |Manifest: NOSIGNATURE
		spawn-animations-1.9.1.jar                        |Spawn Animations              |spawn_animations_mr           |1.9.1               |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2-rc1+1.20.jar     |Player Animator               |playeranimator                |1.0.2-rc1+1.20      |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.22.jar                    |Just Enough Items             |jei                           |15.2.0.22           |DONE      |Manifest: NOSIGNATURE
		VisualWorkbench-v8.0.0-1.20.1-Forge.jar           |Visual Workbench              |visualworkbench               |8.0.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		rubidium-0.6.5.jar                                |Rubidium                      |rubidium                      |0.6.5               |DONE      |Manifest: NOSIGNATURE
		HorseExpert-v8.0.0-1.20.1-Forge.jar               |Horse Expert                  |horseexpert                   |8.0.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		waystones-forge-1.20-14.0.0.jar                   |Waystones                     |waystones                     |14.0.0              |DONE      |Manifest: NOSIGNATURE
		realisticbees-1.20.1-3.4.jar                      |Realistic Bees                |realisticbees                 |3.4                 |DONE      |Manifest: NOSIGNATURE
		more-mobs-1.4.jar                                 |More Mobs                     |more_mobs_mr                  |1.4                 |DONE      |Manifest: NOSIGNATURE
		journeymap-1.20.1-5.9.9-forge.jar                 |Journeymap                    |journeymap                    |5.9.9               |DONE      |Manifest: NOSIGNATURE
		badpackets-forge-0.4.1.jar                        |Bad Packets                   |badpackets                    |0.4.1               |DONE      |Manifest: NOSIGNATURE
		CustomPlayerModels-1.20-0.6.8b.jar                |Customizable Player Models    |cpm                           |0.6.8b              |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-beta.8.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.8        |DONE      |Manifest: NOSIGNATURE
		Kambrik-6.0.1+1.20.1-forge.jar                    |Kambrik                       |kambrik                       |6.0.1+1.20.1        |DONE      |Manifest: NOSIGNATURE
		midnightlib-forge-1.4.1.jar                       |MidnightLib                   |midnightlib                   |1.4.1               |DONE      |Manifest: NOSIGNATURE
		cryingghasts-1.20.1-3.1.jar                       |Crying Ghasts                 |cryingghasts                  |3.1                 |DONE      |Manifest: NOSIGNATURE
		skeletonhorsespawn-1.20.1-3.6.jar                 |Skeleton Horse Spawn          |skeletonhorsespawn            |3.6                 |DONE      |Manifest: NOSIGNATURE
		Rex's-AdditionalStructures-1.20.x-(v.4.1.2).jar   |Additional Structures         |additionalstructures          |4.1.2               |DONE      |Manifest: NOSIGNATURE
		Resourcify (1.20.x-forge)-1.1.0.jar               |Resourcify                    |resourcify                    |1.1.0               |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20-7.0.4.jar                         |Balm                          |balm                          |7.0.4               |DONE      |Manifest: NOSIGNATURE
		vanillazoom-1.20.1-2.1.jar                        |Vanilla Zoom                  |vanillazoom                   |2.1                 |DONE      |Manifest: NOSIGNATURE
		cat_jam-1.0.2.jar                                 |cat_jam                       |cat_jam                       |1.0.2               |DONE      |Manifest: NOSIGNATURE
		dungeons-and-taverns-v2.1.3.jar                   |Dungeons and Taverns          |dungeons_andtaverns_mr        |1-v2.1.3            |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.0.99-forge.jar                    |Cloth Config v10 API          |cloth_config                  |11.0.99             |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.20.1-1.1.1.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.20.1-1.1.1        |DONE      |Manifest: NOSIGNATURE
		3dskinlayers-forge-1.5.3-mc1.20.jar               |3dSkinLayers                  |skinlayers3d                  |1.5.3               |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.0.34-universal.jar                |Forge                         |forge                         |47.0.34             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		stackrefill-1.20.1-4.0.jar                        |Stack Refill                  |stackrefill                   |4.0                 |DONE      |Manifest: NOSIGNATURE
		ctov-3.3.1.jar                                    |ChoiceTheorem's Overhauled Vil|ctov                          |3.3.1               |DONE      |Manifest: NOSIGNATURE
		durabilitytooltip-1.1.4-forge-mc1.20.jar          |Durability Tooltip            |durabilitytooltip             |1.1.4               |DONE      |Manifest: NOSIGNATURE
		emotecraft-for-MC1.20.1-2.2.7-a.build.49-forge.jar|Emotecraft                    |emotecraft                    |2.2.7-a.build.49    |DONE      |Manifest: NOSIGNATURE
		corpse-1.20.1-1.0.3.jar                           |Corpse                        |corpse                        |1.20.1-1.0.3        |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.20.1-2.1.56-beta.jar              |When Dungeons Arise           |dungeons_arise                |2.1.56-1.20.1       |DONE      |Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mob-captains-v2.1.2.jar                           |Mob Captains                  |mob_captains_mr               |1-v2.1.2            |DONE      |Manifest: NOSIGNATURE
		handcrafted-forge-1.20-2.3.2.jar                  |Handcrafted                   |handcrafted                   |2.3.2               |DONE      |Manifest: NOSIGNATURE
		combatroll-forge-1.2.1+1.20.1.jar                 |Combat Roll                   |combatroll                    |1.2.1+1.20.1        |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.10.25_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.10.25             |DONE      |Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.20-2.0.0.jar            |Resourcefulconfig             |resourcefulconfig             |2.0.0               |DONE      |Manifest: NOSIGNATURE
		servercore-forge-1.3.7+1.20.1.jar                 |ServerCore                    |servercore                    |1.3.7+1.20.1        |DONE      |Manifest: NOSIGNATURE
		wthit-forge-8.1.1.jar                             |wthit                         |wthit                         |8.1.1               |DONE      |Manifest: NOSIGNATURE
		Bountiful-6.0.1+1.20.1-forge.jar                  |Bountiful                     |bountiful                     |6.0.1+1.20.1        |DONE      |Manifest: NOSIGNATURE
		kffmod-4.3.0.jar                                  |Kotlin For Forge              |kotlinforforge                |4.3.0               |DONE      |Manifest: NOSIGNATURE
		notenoughanimations-forge-1.6.4-mc1.20.jar        |NotEnoughAnimations Mod       |notenoughanimations           |1.6.4               |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.2.0-beta.3+1.20.1.jar              |Curios API                    |curios                        |5.2.0-beta.3+1.20.1 |DONE      |Manifest: NOSIGNATURE
		oculus-mc1.20-1.6.4.jar                           |Oculus                        |oculus                        |1.6.4               |DONE      |Manifest: NOSIGNATURE
		collective-1.20.1-6.62.jar                        |Collective                    |collective                    |6.62                |DONE      |Manifest: NOSIGNATURE
		camera-1.20.1-1.0.3.jar                           |Camera Mod                    |camera                        |1.20.1-1.0.3        |DONE      |Manifest: NOSIGNATURE
		resourcefullib-forge-1.20.1-2.1.1.jar             |Resourceful Lib               |resourcefullib                |2.1.1               |DONE      |Manifest: NOSIGNATURE
		BetterTridents-v8.0.0-1.20.1-Forge.jar            |Better Tridents               |bettertridents                |8.0.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		pmmo-1.20.1-1.0.1.jar                             |Project MMO                   |pmmo                          |1.0.1               |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.20.1-2.5.0.jar                |AppleSkin                     |appleskin                     |2.5.0+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v8.0.0-1.20.1-Forge (1).jar            |Puzzles Lib                   |puzzleslib                    |8.0.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Enhanced_Celestials-forge-1.20.1-5.0.0.2.jar      |Enhanced Celestials           |enhancedcelestials            |5.0.0.2             |DONE      |Manifest: NOSIGNATURE
		CorgiLib-forge-1.20.1-4.0.0.0.jar                 |CorgiLib                      |corgilib                      |4.0.0.0             |DONE      |Manifest: NOSIGNATURE
		followersteleporttoo-1.20.1-2.1.jar               |Followers Teleport Too        |followersteleporttoo          |2.1                 |DONE      |Manifest: NOSIGNATURE
		waterframes-1.20.1-1.3.1d.jar                     |WaterFrames                   |waterframes                   |1.3.1d              |DONE      |Manifest: NOSIGNATURE
		PlayerRevive_FORGE_v2.0.17_mc1.20.1.jar           |PlayerRevive                  |playerrevive                  |2.0.17              |DONE      |Manifest: NOSIGNATURE
		healingcampfire-1.20.1-5.1.jar                    |Healing Campfire              |healingcampfire               |5.1                 |DONE      |Manifest: NOSIGNATURE
		Essential (forge_1.20.1).jar                      |Essential                     |essential                     |12933+deploy-staging|DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: d54b7609-fdd3-463c-9c92-31df8d34ebd1
	FML: 47.0
	Forge: net.minecraftforge:47.0.34
```

**Comment by mysticdrew** [comment]
This is an issue with JourneyMap, it is fixed in `JourneyMap-1.20.1-5.9.10-forge` should be on curseforge once approved(couple hours from now) and modrinth very soon (couple minutes)
