### ISSUE TITLE
Rendering the book of Shadows (Hexerei mod) crashes the game

### ISSUE THREAD

**Issue by KeeWolf** [Asek3/Oculus#415]
### Minecraft Version

1.18.2

### Oculus Version

oculus-mc1.18.2-1.6.4.jar

### Sodium Version

rubidium-0.5.6.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia Geforce GTX 1070

### Java Version

Java 16

### Reproduction Steps

1. Install the [Hexerei](https://www.curseforge.com/minecraft/mc-mods/hexerei) and [Visual Workbench](https://www.curseforge.com/minecraft/mc-mods/visual-workbench) mod!
2. Craft the Book of Shadows from the Hexerei mod!
3. The game should crash from rendering the Book of Shadows on top of the workbench
4. The game keeps crashing every time you log in and it tries rendering the Book of Shadows

log of first crash: [2023-07-16-1.log](https://github.com/Asek3/Oculus/files/12063052/2023-07-16-1.log)

log of consecutive crashes: [2023-07-16-3.log](https://github.com/Asek3/Oculus/files/12063053/2023-07-16-3.log)
Crash Report: [crash-2023-07-15_23.24.39-client.txt](https://github.com/Asek3/Oculus/files/12063023/crash-2023-07-15_23.24.39-client.txt)

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 7/15/23, 11:24 PM
Description: Rendering Block Entity

java.lang.ClassCastException: class net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher$$Lambda$30431/0x00000008034bac88 cannot be cast to class net.minecraft.client.renderer.MultiBufferSource$BufferSource (net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher$$Lambda$30431/0x00000008034bac88 and net.minecraft.client.renderer.MultiBufferSource$BufferSource are in module minecraft@1.18.2 of loader 'TRANSFORMER' @1291aab5)
	at net.joefoxe.hexerei.item.custom.HexereiBookItemRenderer.renderTileStuff(HexereiBookItemRenderer.java:199) ~[hexerei-0.2.2.jar%23158!/:0.2.2] {re:classloading}
	at net.joefoxe.hexerei.item.custom.HexereiBookItemRenderer.renderByItem(HexereiBookItemRenderer.java:77) ~[hexerei-0.2.2.jar%23158!/:0.2.2] {re:classloading}
	at net.joefoxe.hexerei.item.custom.CustomItemRendererWithPageDrawing$Renderer.m_108829_(CustomItemRendererWithPageDrawing.java:42) ~[hexerei-0.2.2.jar%23158!/:0.2.2] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115143_(ItemRenderer.java:159) ~[client-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at fuzs.visualworkbench.client.renderer.blockentity.WorkbenchTileEntityRenderer.renderResultItem(WorkbenchTileEntityRenderer.java:91) ~[VisualWorkbench-v3.3.0-1.18.2-Forge.jar%23249!/:3.3.0] {re:classloading}
	at fuzs.visualworkbench.client.renderer.blockentity.WorkbenchTileEntityRenderer.render(WorkbenchTileEntityRenderer.java:41) ~[VisualWorkbench-v3.3.0-1.18.2-Forge.jar%23249!/:3.3.0] {re:classloading}
	at fuzs.visualworkbench.client.renderer.blockentity.WorkbenchTileEntityRenderer.m_6922_(WorkbenchTileEntityRenderer.java:22) ~[VisualWorkbench-v3.3.0-1.18.2-Forge.jar%23249!/:3.3.0] {re:classloading}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112284_(BlockEntityRenderDispatcher.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcher,pl:mixin:APP:mixins.oculus.json:entity_render_context.MixinBlockEntityRenderDispatcher,pl:mixin:APP:rubidium_extras.mixins.json:EntityDistance.MaxDistanceTileEntity,pl:mixin:APP:flywheel.mixins.json:BlockEntityRenderDispatcherAccessor,pl:mixin:APP:entityculling.mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:APP:enhancedblockentities.mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:A}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112297_(BlockEntityRenderDispatcher.java:73) ~[client-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcher,pl:mixin:APP:mixins.oculus.json:entity_render_context.MixinBlockEntityRenderDispatcher,pl:mixin:APP:rubidium_extras.mixins.json:EntityDistance.MaxDistanceTileEntity,pl:mixin:APP:flywheel.mixins.json:BlockEntityRenderDispatcherAccessor,pl:mixin:APP:entityculling.mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:APP:enhancedblockentities.mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:A}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:98) ~[client-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcher,pl:mixin:APP:mixins.oculus.json:entity_render_context.MixinBlockEntityRenderDispatcher,pl:mixin:APP:rubidium_extras.mixins.json:EntityDistance.MaxDistanceTileEntity,pl:mixin:APP:flywheel.mixins.json:BlockEntityRenderDispatcherAccessor,pl:mixin:APP:entityculling.mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:APP:enhancedblockentities.mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:A}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112267_(BlockEntityRenderDispatcher.java:73) ~[client-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:BlockEntityRendererDispatcher,pl:mixin:APP:mixins.oculus.json:entity_render_context.MixinBlockEntityRenderDispatcher,pl:mixin:APP:rubidium_extras.mixins.json:EntityDistance.MaxDistanceTileEntity,pl:mixin:APP:flywheel.mixins.json:BlockEntityRenderDispatcherAccessor,pl:mixin:APP:entityculling.mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:APP:enhancedblockentities.mixins.json:BlockEntityRenderDispatcherMixin,pl:mixin:A}
	at net.coderbot.iris.pipeline.ShadowRenderer.renderBlockEntities(ShadowRenderer.java:576) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?] {re:mixin,re:classloading}
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:494) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?] {re:mixin,re:classloading}
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:1026) ~[oculus-mc1.18.2-1.6.4.jar%23203!/:?] {re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.handler$bbo000$iris$renderTerrainShadows(LevelRenderer.java:10124) ~[client-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1150) ~[client-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:render,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1061) ~[client-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:835) ~[client-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immediatelyfast.mixins.json:hud_batching.MixinMinecraftClient,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixin.cleancut.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:mixins.codechickenlib.json:MinecraftMixin,pl:mixin:APP:fastload.mixins.json:client.MinecraftClientMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:ding.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor,pl:mixin:APP:globaldataandresourcepacks.mixins.json:ClientPackFinderMixin,pl:mixin:APP:puzzleslib.forge.mixins.json:client.MinecraftForgeMixin,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immediatelyfast.mixins.json:hud_batching.MixinMinecraftClient,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:mixin.cleancut.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:mixins.codechickenlib.json:MinecraftMixin,pl:mixin:APP:fastload.mixins.json:client.MinecraftClientMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:ding.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor,pl:mixin:APP:globaldataandresourcepacks.mixins.json:ClientPackFinderMixin,pl:mixin:APP:puzzleslib.forge.mixins.json:client.MinecraftForgeMixin,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23260!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.9.jar%2318!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
```

### Additional context

We're using Oculus as part of a modpack, as the list of installed mods in the crash report will suggest, but we confidently identified Hexerei and Oculus as the main trouble makers. We did make some assumptions on the way there though, but in that case the full log files are here. All crashes occurred on a dedicated server, though only the client crashed.

A similar issue also occurred when putting the Book of Shadows in a container, like a barrel, resulting in the game crashing.
Barrel Crash: [latest.log](https://github.com/Asek3/Oculus/files/12063046/latest.log)
For some reason there was no crash report generated for this second crash.

**Comment by KeeWolf** [comment]
Update: I've successfully recreated the crash. The game also consistently crashes when rendering the Book of Shadows in the player's hand.

Crash Report upon crafting (with Visual Workbench): [crash-2023-07-16_12.45.10-client.txt](https://github.com/Asek3/Oculus/files/12063811/crash-2023-07-16_12.45.10-client.txt)
Log file: [2023-07-16-2.log](https://github.com/Asek3/Oculus/files/12063818/2023-07-16-2.log)

Crash Report upon taking in hand: [crash-2023-07-16_12.47.53-client.txt](https://github.com/Asek3/Oculus/files/12063813/crash-2023-07-16_12.47.53-client.txt)
Log file: [latest.log](https://github.com/Asek3/Oculus/files/12063816/latest.log)

**Comment by Reindolf66** [comment]
I'm having the same crash. I'm playing with someone else, he does not have any issues despite confirming we have the same graphics settings. I'm wondering if it's possible this is a crash related to Nvidia GPUs, though that's purely speculation at this point. I'll post another comment if I find a fix.

**Comment by AsterionXeity** [comment]
Same happened to me when loading shaders, with works till you toggle them on [https://pastebin.com/raw/m1D7uhss](url)
Also runnin gon a NVIDIA GPU.

**Comment by Rhyssia** [comment]
Here to report same/similar issue. Crashing when I added book with JEI and tried to hold it in my hand with shaders on.
Minecraft: [1.18.2]
Relatable Mods: [hexerei-0.2.2.jar]

Crash Report
[crash-2023-10-01_14.41.44-client.txt](https://github.com/Asek3/Oculus/files/12777969/crash-2023-10-01_14.41.44-client.txt)
