### ISSUE TITLE
Game Crashes when lava touches leaves

### ISSUE THREAD

**Issue by Nat0r123** [Asek3/Oculus#471]
### Minecraft Version

1.20.1

### Oculus Version

1.6.9

### Sodium Version

rubidium 0.7.1

### Operating System

Windows 10

### What is your GPU?

RTX 4090

### Java Version

Java 17

### Reproduction Steps

1. Place a Leaf Block. Oak Leaves, Birch, doesnt matter.
2. Place lava via bucket next to leaves
3. crash

The crash also happens if naturally generated lava touches leaves.

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// This doesn't make any sense!
Time: 2023-10-03 03:16:29
Description: Encountered exception while building chunk meshes
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m_118367_(double)" because "sprite" is null
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer.render(FluidRenderer.java:340) ~[rubidium-mc1.20.1-0.7.1.jar%23159!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:separate_ao.MixinFluidRenderer,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:125) ~[rubidium-mc1.20.1-0.7.1.jar%23159!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:45) ~[rubidium-mc1.20.1-0.7.1.jar%23159!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:block_id.MixinChunkRenderRebuildTask,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[rubidium-mc1.20.1-0.7.1.jar%23159!/:?] {re:computing_frames,re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[rubidium-mc1.20.1-0.7.1.jar%23159!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
```

### Additional context

Shaders turned on/off doesn't matter. 
The only mods that have been installed were oculus and rubidium.
tested on old saves and new worlds for bugtesting.

**Comment by Nat0r123** [comment]
addendum: crash does not happen with water.

**Comment by Nat0r123** [comment]
edit: seems to be a rubidium issue. The're already fixing it for the next release: https://github.com/Reforged-Hub/rubidium-upstream/commit/86966a781bc2b7b31c3b95cd521ba5a0f1bf11c0

**Comment by ThePyroGod** [comment]
Excited for the fix!

**Comment by Ubasnoz** [comment]
> edit: seems to be a rubidium issue. The're already fixing it for the next release: [Reforged-Hub/rubidium-upstream@86966a7](https://github.com/Reforged-Hub/rubidium-upstream/commit/86966a781bc2b7b31c3b95cd521ba5a0f1bf11c0)

Hey, where do you put this in the config file?

**Comment by CaptainCortisol** [comment]
Anybody having this issue. I fixed it by installing embeddium as a replacement for rubidium for the time being.
