### ISSUE TITLE
Oculus incompatible with Mohist 

### ISSUE THREAD

**Issue by SoyJetixXD** [Asek3/Oculus#527]
### Minecraft Version

Minecraft 1.16.5

### Oculus Version

oculus-mc1.16.5-1.4.7

### Sodium Version

rubidium-mc1.16.5-0.2.13

### Operating System

Windows 11

### What is your GPU?

NVIDIA GeForce RTX 3050

### Java Version

Java 8

### Reproduction Steps

1)Create a server with Mohist (plugins + mods)
2)Start the server
3)Game Crashes

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 01/01/24 03:39 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:72) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:37) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:136) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_381] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_381] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_381] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37) ~[MOHIST.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) ~[modlauncher-mohist-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) ~[modlauncher-mohist-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) ~[modlauncher-mohist-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) ~[modlauncher-mohist-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-mohist-8.1.3.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:105) ~[MOHIST.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:102) ~[MOHIST.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:86) ~[MOHIST.jar:?] {re:classloading,re:classloading,re:classloading,re:classloading}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[MOHIST.jar:36.2] {}
-- MOD oculus --
Details:
	Mod File: oculus-mc1.16.5-1.4.7.jar
	Failure message: Oculus has class loading errors
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER
	Mod Version: 1.4.7
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[MOHIST.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-mohist-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-mohist-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:290) ~[modlauncher-mohist-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:160) ~[modlauncher-mohist-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:109) ~[modlauncher-mohist-8.1.3.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_381] {}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_381] {}
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_381] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:48) ~[forge:36.2] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_381] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_381] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_381] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_381] {}
	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:62) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:291) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$buildMods$30(ModLoader.java:270) ~[forge:?] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_381] {}
	at java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_381] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_381] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_381] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_381] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_381] {}
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_381] {}
	at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:272) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:170) ~[forge:?] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_381] {}
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_381] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_381] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_381] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_381] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_381] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_381] {}
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_381] {}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:172) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:30) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:136) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_381] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_381] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_381] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37) ~[MOHIST.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) ~[modlauncher-mohist-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) ~[modlauncher-mohist-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) ~[modlauncher-mohist-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) ~[modlauncher-mohist-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) ~[modlauncher-mohist-8.1.3.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:105) ~[MOHIST.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:102) ~[MOHIST.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:86) ~[MOHIST.jar:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Mohist Version: 1.16.5-1198
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_381, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1161705184 bytes (1107 MB) / 1551368192 bytes (1479 MB) up to 2863661056 bytes (2731 MB)
	CPUs: 12
	JVM Flags: 2 total; -Xms1024M -Xmx3G
	ModLauncher: mohist-8.1.3
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/MOHIST.jar object_holder_definalize PLUGINSERVICE 
		/MOHIST.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/MOHIST.jar capability_inject_definalize PLUGINSERVICE 
		/MOHIST.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/MOHIST.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: com.mohistmc:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		mohist-1.16.5-1198-server.jar                     |Minecraft                     |minecraft                     |1.16.5              |NONE      |Manifest: NOSIGNATURE
		saturn-mc1.16.5-0.0.3.jar                         |Saturn                        |saturn                        |0.0.3               |NONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.8.0.1009.jar                         |Just Enough Items             |jei                           |7.8.0.1009          |NONE      |Manifest: NOSIGNATURE
		SpawnerFix-1.16.2-1.0.0.2.jar                     |Spawner Fix                   |sf                            |1.0.0.2             |NONE      |Manifest: NOSIGNATURE
		connectivity-2.4-1.16.5.jar                       |Connectivity Mod              |connectivity                  |2.4-1.16.5          |NONE      |Manifest: NOSIGNATURE
		TextruesRubidiumOptions-1.0.8-mc1.16.5.jar        |TexTrue's Rubidium Options    |reeses_sodium_options         |1.0.8-mc1.16.5      |NONE      |Manifest: NOSIGNATURE
		rubidium-mc1.16.5-0.2.13.jar                      |Rubidium                      |rubidium                      |0.2.13              |NONE      |Manifest: NOSIGNATURE
		Iceberg-1.16.5-1.0.45.jar                         |Iceberg                       |iceberg                       |1.0.45              |NONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.4.jar                        |Waystones                     |waystones                     |7.6.4               |NONE      |Manifest: NOSIGNATURE
		oculus-mc1.16.5-1.4.7.jar                         |Oculus                        |oculus                        |1.4.7               |NONE      |Manifest: NOSIGNATURE
		Clumps-6.0.0.28.jar                               |Clumps                        |clumps                        |6.0.0.28            |NONE      |Manifest: NOSIGNATURE
		RoadRunner-mc1.16.5-1.5.1.jar                     |RoadRunner                    |roadrunner                    |1.5.1               |NONE      |Manifest: NOSIGNATURE
		netheritehorsearmor-1.7.jar                       |Netherite Horse Armor Mod     |netheritehorsearmor           |1.7                 |NONE      |Manifest: NOSIGNATURE
		elevatorid-1.16.5-1.7.13.jar                      |Elevator Mod                  |elevatorid                    |1.16.5-1.7.13       |NONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.4.33.jar                |Bookshelf                     |bookshelf                     |10.4.33             |NONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Tips-1.16.5-4.0.18.jar                            |Tips                          |tips                          |4.0.18              |NONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		lazydfu-0.1.3.jar                                 |LazyDFU                       |lazydfu                       |0.1.3               |NONE      |Manifest: NOSIGNATURE
		ferritecore-2.1.1-forge.jar                       |Ferrite Core                  |ferritecore                   |2.1.1               |NONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		mohist-1.16.5-1198-universal.jar                  |Forge                         |forge                         |36.2.39             |NONE      |Manifest: NOSIGNATURE
		Waddles-1.16.5-0.8.13.jar                         |Waddles                       |waddles                       |1.16.5-0.8.13       |NONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.5.1.jar                |AppleSkin                     |appleskin                     |2.5.1+mc1.16.4      |NONE      |Manifest: NOSIGNATURE
		FastLeafDecay-v25.2.jar                           |FastLeafDecay                 |fastleafdecay                 |v25.2               |NONE      |Manifest: NOSIGNATURE
		voidtotem-1.16.5-1.4.0.jar                        |Void Totem                    |voidtotem                     |1.16.5-1.4.0        |NONE      |Manifest: NOSIGNATURE
		stables-1.16.5-1.0.1.jar                          |Stables                       |stables                       |1.16.5-1.0.1        |NONE      |Manifest: NOSIGNATURE
		DarkPaintings-1.16.5-6.0.11.jar                   |DarkPaintings                 |darkpaintings                 |6.0.11              |NONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		AdvancementPlaques-1.16.5-1.4.1.jar               |Advancement Plaques           |advancementplaques            |1.4.1               |NONE      |Manifest: NOSIGNATURE
		chocolate-1.3.0-1.16.4.jar                        |Chocolate                     |chocolate                     |1.3.0-1.16.4        |NONE      |Manifest: NOSIGNATURE
	CraftBukkit Information: 
   Running: 
   Failed to handle CraftCrashReport: craftbukkit not runs
```

### Additional context

Hello!
I'm organizing a mod server with my friends and obviously your mod can't be missing, it's fantastic!
But unfortunately when testing the mods with the server the game crashed.
We have tested the mods one by one until we confirmed that it was the _**Oculus**_ that was causing the problem.
Please give me a hand!
**PS: We are using the latest available version of the Mohist installer**

**Comment by Xplodin** [comment]
Bruh
Oculus isnt at fault here.
Its a client side mod
