### ISSUE TITLE
Oculus 1.6.13 Squared Text issue

### ISSUE THREAD

**Issue by Dracu0** [Asek3/Oculus#537]
### What happened?

I made a modpack, and it works perfectly fine with oculus 1.6.9, but when using 1.6.13 all of the game's text becomes a bunch of boxes.

In the logs below, you can see a texture error right at the end of the log, check "Additional context".

[Modlist.txt](https://github.com/Asek3/Oculus/files/14065141/Modlist.txt)

### Screenshots

![Screenshot_11](https://github.com/Asek3/Oculus/assets/33703043/54465f19-7b15-4c88-bd6a-0eddafc407d0)

### Relevant log output

```shell
Crash Report UUID: 7b9a20a2-430c-41bf-b7f9-ec5a3e644b2d
	FML: 47.2
	Forge: net.minecraftforge:47.2.20
	Flywheel Backend: GL33 Instanced Arrays
	Suspected Mods: Minecraft (minecraft), Oculus Flywheel Compat (irisflw)
[26Jan2024 13:06:12.820] [Render thread/INFO] [defaultoptions/]: Loaded default options for keymappings
[26Jan2024 13:06:12.823] [Thread-46/INFO] [com.mojang.blaze3d.platform.GlDebug/]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.'
[26Jan2024 13:06:12.823] [Thread-46/INFO] [com.mojang.blaze3d.platform.GlDebug/]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.'
[26Jan2024 13:06:13.612] [Render thread/WARN] [ModernFix/]: Game took 74.55 seconds to start
[26Jan2024 13:06:15.325] [Render thread/INFO] [Oculus/]: Creating pipeline for dimension NamespacedId{namespace='minecraft', name='overworld'}
[26Jan2024 13:06:15.352] [Render thread/INFO] [Oculus/]: Starting custom uniform resolving
[26Jan2024 13:06:17.768] [Render thread/WARN] [Oculus/]: Error while parsing the block ID map entry for "block.10092":
[26Jan2024 13:06:17.769] [Render thread/WARN] [Oculus/]: - The block minecraft:stone has no property with the name variant, ignoring!
[26Jan2024 13:06:17.770] [Render thread/WARN] [Oculus/]: Error while parsing the block ID map entry for "block.10152":
[26Jan2024 13:06:17.772] [Render thread/WARN] [Oculus/]: - The block minecraft:stone_slab has no property with the name variant, ignoring!
[26Jan2024 13:06:17.773] [Render thread/WARN] [Oculus/]: Error while parsing the block ID map entry for "block.60016":
[26Jan2024 13:06:17.773] [Render thread/WARN] [Oculus/]: - The block minecraft:dragon_head has no property with the name powered, ignoring!
[26Jan2024 13:06:17.777] [Render thread/WARN] [Oculus/]: Error while parsing the block ID map entry for "block.10240":
[26Jan2024 13:06:17.777] [Render thread/WARN] [Oculus/]: - The block minecraft:stone_slab has no property with the name variant, ignoring!
[26Jan2024 13:06:17.778] [Render thread/WARN] [Oculus/]: Error while parsing the block ID map entry for "block.60036":
[26Jan2024 13:06:17.778] [Render thread/WARN] [Oculus/]: - The block minecraft:dragon_head has no property with the name powered, ignoring!
[26Jan2024 13:06:17.779] [Render thread/WARN] [Oculus/]: Error while parsing the block ID map entry for "block.10364":
[26Jan2024 13:06:17.779] [Render thread/WARN] [Oculus/]: - The block minecraft:stone_slab has no property with the name variant, ignoring!
[26Jan2024 13:06:17.779] [Render thread/WARN] [Oculus/]: Error while parsing the block ID map entry for "block.10100":
[26Jan2024 13:06:17.779] [Render thread/WARN] [Oculus/]: - The block minecraft:stone has no property with the name variant, ignoring!
[26Jan2024 13:06:17.779] [Render thread/WARN] [Oculus/]: Error while parsing the block ID map entry for "block.10084":
[26Jan2024 13:06:17.779] [Render thread/WARN] [Oculus/]: - The block minecraft:stone has no property with the name variant, ignoring!
[26Jan2024 13:06:17.780] [Render thread/WARN] [Oculus/]: Error while parsing the block ID map entry for "block.10032":
[26Jan2024 13:06:17.780] [Render thread/WARN] [Oculus/]: - The block minecraft:stone_slab has no property with the name variant, ignoring!
[26Jan2024 13:06:17.780] [Render thread/WARN] [Oculus/]: Error while parsing the block ID map entry for "block.10088":
[26Jan2024 13:06:17.780] [Render thread/WARN] [Oculus/]: - The block minecraft:stone has no property with the name variant, ignoring!
[26Jan2024 13:06:17.780] [Render thread/WARN] [Oculus/]: Error while parsing the block ID map entry for "block.10104":
[26Jan2024 13:06:17.780] [Render thread/WARN] [Oculus/]: - The block minecraft:stone has no property with the name variant, ignoring!
[26Jan2024 13:06:17.780] [Render thread/WARN] [Oculus/]: Error while parsing the block ID map entry for "block.10096":
[26Jan2024 13:06:17.780] [Render thread/WARN] [Oculus/]: - The block minecraft:stone has no property with the name variant, ignoring!
[26Jan2024 13:06:17.781] [Render thread/WARN] [Oculus/]: Error while parsing the block ID map entry for "block.10416":
[26Jan2024 13:06:17.781] [Render thread/WARN] [Oculus/]: - The block minecraft:stone_slab has no property with the name variant, ignoring!
[26Jan2024 13:06:17.799] [Render thread/INFO] [HammerLib/]: Registered custom glint render buffers.
[26Jan2024 13:06:19.117] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!
[26Jan2024 13:06:19.136] [Render thread/ERROR] [net.minecraft.client.Minecraft/]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.client.renderer.texture.TextureManager.close(TextureManager.java:178) ~[client-1.20.1-20230612.114412-srg.jar%23668!/:?]
	at net.minecraft.client.Minecraft.close(Minecraft.java:1070) ~[client-1.20.1-20230612.114412-srg.jar%23668!/:?]
	at net.minecraft.client.Minecraft.m_91393_(Minecraft.java:1043) ~[client-1.20.1-20230612.114412-srg.jar%23668!/:?]
	at net.minecraft.client.main.Main.main(Main.java:234) ~[forge-47.2.20.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.20.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.20.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
```

### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.6.13

### Rubidium Version

rubidium-mc1.20.1-0.7.1a

### Operating System

Windows 11

### What is your GPU?

RTX 3080 12GB

### Java Version

Java 19.0.1

**Comment by Dracu0** [comment]
Disabling Embeddium version 0.2.18 seems to make the issue go away, also it directly conflicts with rubidium saying it's a duplicate.
