### ISSUE TITLE
Incompatibility With Figura Mod on Forge

### ISSUE THREAD

**Issue by ghost** [Asek3/Oculus#548]
### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.6.15

### Rubidium / Embeddium Version

embeddium-0.3.1+mc1.20.1

### Operating System

win 11

### What is your GPU?

rtx 3070

### Java Version

jdk 17

### Reproduction Steps

launch game with both mods

### Crash Report file and latest.log

```shell
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 15 more
Caused by: java.lang.ExceptionInInitializerError
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.resources.ResourceKey.m_135788_(ResourceKey.java:26)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.registries.Registries.m_257397_(Registries.java:200)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.registries.Registries.<clinit>(Registries.java:93)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.flag.FeatureElement.<clinit>(FeatureElement.java:18)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:45)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.Items.<clinit>(Items.java:21)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.entity.ItemRenderer.<clinit>(ItemRenderer.java:51)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.RenderType.<clinit>(RenderType.java:101)
	at TRANSFORMER/figura@0.1.2+1.20.1/forge.org.figuramc.figura.model.rendering.texture.RenderTypes.<clinit>(RenderTypes.java:27)
	at TRANSFORMER/figura@0.1.2+1.20.1/forge.org.figuramc.figura.lua.docs.FiguraListDocs$2.<init>(FiguraListDocs.java:44)
	at TRANSFORMER/figura@0.1.2+1.20.1/forge.org.figuramc.figura.lua.docs.FiguraListDocs.<clinit>(FiguraListDocs.java:43)
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.platform.InputConstants$Type.handler$gok000$addKey(InputConstants.java:515)
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.platform.InputConstants$Type.m_84899_(InputConstants.java)
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.platform.InputConstants$Type.<clinit>(InputConstants.java:214)
	at TRANSFORMER/oculus@1.6.15/net.coderbot.iris.Iris.<clinit>(Iris.java:95)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.SystemReport.handler$bhm000$fillSystemDetails(SystemReport.java:523)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.SystemReport.<init>(SystemReport.java:58)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.CrashReport.<init>(CrashReport.java:31)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.CrashReport.m_127529_(CrashReport.java:216)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:149)
	... 23 more
Caused by: java.lang.IllegalArgumentException: Not bootstrapped (called from registry ResourceKey[minecraft:root / minecraft:root])
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.m_179916_(Bootstrap.java:113)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.m_179912_(Bootstrap.java:106)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.MappedRegistry.<init>(MappedRegistry.java:85)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.MappedRegistry.<init>(MappedRegistry.java:81)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.registries.BuiltInRegistries.<clinit>(BuiltInRegistries.java:113)
	... 43 more
```

### Additional context

issue reported on Figura github [here](https://github.com/FiguraMC/Figura/issues/176)

**Comment by UnlikePaladin** [comment]
Hi one of the developers of the Figura mod here, our mod has always worked fine with Iris on Fabric and we don't actually have any platform specific code that should be causing it to crash, could we know why the issue was closed as invalid and not planned if this is an Oculus issue? We've had several users report this problem and apparently older Oculus releases worked fine so this is relatively new.

**Comment by dima-dencep** [comment]
What do you want us to do, not register key bindings or what?

**Comment by UnlikePaladin** [comment]
I'd like it if the keybind's creation matched upstream's behavior, you guys are creating your keybinds on class load which is too early, it could cause issues for mods other than us as well, because it's not safe to do so yet, upstream Iris, (and Oculus previously matched this) create their keybinds on the onEarlyInitialize method. If the initialization is moved back to onEarlyInitialize it should fix the problem. I'm not asking for much here, it really is a trivial fix.

**Comment by UnlikePaladin** [comment]
And fyi, you introduced this issue on your own two weeks ago with your merge, please be more careful is possible in the future, Oculus is an important mod for some people.
[https://github.com/Asek3/Oculus/blame/22f576e6b077231507ac8ad4765421f39c777fa4/src/main/java/net/coderbot/iris/Iris.java#L95](https://github.com/Asek3/Oculus/blame/22f576e6b077231507ac8ad4765421f39c777fa4/src/main/java/net/coderbot/iris/Iris.java#L95)

**Comment by dima-dencep** [comment]
Iris will soon replace oculus 😼

**Comment by UnlikePaladin** [comment]
lol I'm well aware that an official Iris port might be coming soon but it's still an easy fix and until that happens people will continue to use Oculus, besides Iris might not support older versions which Oculus still updates occasionally so users are affected anyway
