### ISSUE TITLE
Figura crash

### ISSUE THREAD

**Issue by xg787** [Asek3/Oculus#558]
### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.6.15a.jar

### Rubidium / Embeddium Version

embeddium-0.3.4+mc1.20.1.jar

### Operating System

Windows 10

### What is your GPU?

NVIDIA GeForce RTX 3070

### Java Version

17.0.9

### Reproduction Steps

1. Start game with Figura
2. Game Crashes

### Crash Report file and latest.log

```shell
2024-02-17 14:52:55,766 main WARN Advanced terminal features are not available in this environment
[14:52:55] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, {MINECRAFT_USERNAME}, --version, 1.20.1, --gameDir, C:\Minecraft\com.modrinth.theseus\profiles\test (1), --assetsDir, C:\Minecraft\com.modrinth.theseus\meta\assets, --assetIndex, 5, --uuid, {MINECRAFT_UUID}, --accessToken, ????????, --clientId, c4502edb-87c6-40cb-b595-64a280cf8906, --xuid, 0, --userType, msa, --versionType, release, --width, 854, --height, 480, --launchTarget, forgeclient, --fml.forgeVersion, 47.2.17, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[14:52:55] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.9 by Azul Systems, Inc.; OS Windows 10 arch amd64 version 10.0
[14:52:56] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[LWJGL] Version: 3.3.1 build 7
[LWJGL] 	 OS: Windows 10 v10.0
[LWJGL] 	JRE: Windows amd64 17.0.9
[LWJGL] 	JVM: OpenJDK 64-Bit Server VM v17.0.9+8-LTS by Azul Systems, Inc.
[LWJGL] Loading JNI library: lwjgl
[LWJGL] 	Module: org.lwjgl
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Minecraft\com.modrinth.theseus\meta\natives\1.20.1-1.20.1-47.2.17\lwjgl.dll
[LWJGL] Loading library: glfw
[LWJGL] 	Module: org.lwjgl.glfw
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Minecraft\com.modrinth.theseus\meta\natives\1.20.1-1.20.1-47.2.17\glfw.dll
[14:52:56] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[14:52:56] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6
[LWJGL] Loading library: jemalloc
[LWJGL] 	Module: org.lwjgl.jemalloc
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Minecraft\com.modrinth.theseus\meta\natives\1.20.1-1.20.1-47.2.17\jemalloc.dll
[LWJGL] MemoryUtil allocator: JEmallocAllocator
[LWJGL] Loading JNI library: lwjgl_stb
[LWJGL] 	Module: org.lwjgl.stb
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Minecraft\com.modrinth.theseus\meta\natives\1.20.1-1.20.1-47.2.17\lwjgl_stb.dll
[LWJGL] Java 10 memcpy enabled
[LWJGL] Java 9 check intrinsics enabled
[LWJGL] Closure Registry: simple
[LWJGL] Loading JNI library: lwjgl_opengl
[LWJGL] 	Module: org.lwjgl.opengl
[14:52:56] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Minecraft/com.modrinth.theseus/meta/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23144!/ Service=ModLauncher Env=CLIENT
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Minecraft\com.modrinth.theseus\meta\natives\1.20.1-1.20.1-47.2.17\lwjgl_opengl.dll
[LWJGL] Loading library: opengl32
[LWJGL] 	Module: org.lwjgl.opengl
[LWJGL] 	opengl32.dll not found in org.lwjgl.librarypath=C:\Minecraft\com.modrinth.theseus\meta\natives\1.20.1-1.20.1-47.2.17
[LWJGL] 	Loaded from system paths: C:\Windows\SYSTEM32\opengl32.dll
[LWJGL] Java 10 multiplyHigh enabled
[LWJGL] Java 9 text decoding enabled
[14:52:56] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 4.6.0 NVIDIA 545.84, NVIDIA Corporation
[14:52:57] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Minecraft\com.modrinth.theseus\meta\libraries\net\minecraftforge\fmlcore\1.20.1-47.2.17\fmlcore-1.20.1-47.2.17.jar is missing mods.toml file
[14:52:57] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Minecraft\com.modrinth.theseus\meta\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.2.17\javafmllanguage-1.20.1-47.2.17.jar is missing mods.toml file
[14:52:57] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Minecraft\com.modrinth.theseus\meta\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.2.17\lowcodelanguage-1.20.1-47.2.17.jar is missing mods.toml file
[14:52:57] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Minecraft\com.modrinth.theseus\meta\libraries\net\minecraftforge\mclanguage\1.20.1-47.2.17\mclanguage-1.20.1-47.2.17.jar is missing mods.toml file
[14:52:57] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 4 dependencies adding them to mods collection
[14:52:58] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[14:52:58] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.1, --gameDir, C:\Minecraft\com.modrinth.theseus\profiles\test (1), --assetsDir, C:\Minecraft\com.modrinth.theseus\meta\assets, --uuid, {MINECRAFT_UUID}, --username, {MINECRAFT_USERNAME}, --assetIndex, 5, --accessToken, ????????, --clientId, c4502edb-87c6-40cb-b595-64a280cf8906, --xuid, 0, --userType, msa, --versionType, release, --width, 854, --height, 480]
[14:52:59] [main/INFO] [Embeddium/]: Loaded configuration file for Embeddium: 50 options available, 3 override(s) found
[14:52:59] [main/INFO] [Embeddium-GraphicsAdapterProbe/]: Searching for graphics cards...
[14:52:59] [main/INFO] [Embeddium-GraphicsAdapterProbe/]: Found graphics card: GraphicsAdapterInfo[vendor=NVIDIA, name=NVIDIA GeForce RTX 3070, version=DriverVersion=31.0.15.4584]
[14:52:59] [main/WARN] [Embeddium-Workarounds/]: Sodium has applied one or more workarounds to prevent crashes or other issues on your system: [NVIDIA_THREADED_OPTIMIZATIONS]
[14:52:59] [main/WARN] [Embeddium-Workarounds/]: This is not necessarily an issue, but it may result in certain features or optimizations being disabled. You can sometimes fix these issues by upgrading your graphics driver.
[14:52:59] [main/WARN] [mixin/]: Error loading class: de/maxhenkel/voicechat/voice/client/RenderEvents (java.lang.ClassNotFoundException: de.maxhenkel.voicechat.voice.client.RenderEvents)
[14:53:00] [main/WARN] [Embeddium/]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [oculus]) disables it and children
[14:53:00] [main/WARN] [Embeddium/]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [oculus]) disables it and children
[14:53:00] [main/WARN] [Embeddium/]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [oculus]) disables it and children
[14:53:00] [main/WARN] [Embeddium/]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [oculus]) disables it and children
[14:53:00] [main/WARN] [Embeddium/]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [oculus]) disables it and children
[14:53:00] [main/WARN] [Embeddium/]: Force-disabling mixin 'features.render.entity.fast_render.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [oculus]) disables it and children
[14:53:00] [main/WARN] [Embeddium/]: Force-disabling mixin 'features.render.entity.fast_render.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [oculus]) disables it and children
[14:53:00] [main/WARN] [Embeddium/]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [oculus]) disables it and children
[14:53:01] [main/WARN] [mixin/]: Injection warning: LVT in net/minecraft/client/renderer/GameRenderer::m_109089_(FJLcom/mojang/blaze3d/vertex/PoseStack;)V has incompatible changes at opcode 264 in callback forge-figura-common.mixins.json:render.GameRendererMixin->@Inject::renderLevelSaveBobbingOF(FJLcom/mojang/blaze3d/vertex/PoseStack;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;ZZLnet/minecraft/client/Camera;Lcom/mojang/blaze3d/vertex/PoseStack;D)V.
 Expected: [Z, Z, Lnet/minecraft/client/Camera;, Lcom/mojang/blaze3d/vertex/PoseStack;, D]
    Found: [Z, Lnet/minecraft/client/Camera;, Lcom/mojang/blaze3d/vertex/PoseStack;, D, F]
Available: [Z, Lnet/minecraft/client/Camera;, Lcom/mojang/blaze3d/vertex/PoseStack;, D, F, F, I, F, Lcom/mojang/math/Axis;, F]
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.17/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.17/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.17/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 7 more
Caused by: java.lang.ExceptionInInitializerError
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.resources.ResourceKey.m_135788_(ResourceKey.java:26)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.registries.Registries.m_257397_(Registries.java:200)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.registries.Registries.<clinit>(Registries.java:93)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.flag.FeatureElement.<clinit>(FeatureElement.java:18)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:45)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.Items.<clinit>(Items.java:21)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.entity.ItemRenderer.<clinit>(ItemRenderer.java:51)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.RenderType.<clinit>(RenderType.java:101)
	at TRANSFORMER/figura@0.1.2+1.20.1/forge.org.figuramc.figura.model.rendering.texture.RenderTypes.<clinit>(RenderTypes.java:27)
	at TRANSFORMER/figura@0.1.2+1.20.1/forge.org.figuramc.figura.lua.docs.FiguraListDocs$2.<init>(FiguraListDocs.java:44)
	at TRANSFORMER/figura@0.1.2+1.20.1/forge.org.figuramc.figura.lua.docs.FiguraListDocs.<clinit>(FiguraListDocs.java:43)
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.platform.InputConstants$Type.handler$zbg000$addKey(InputConstants.java:515)
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.platform.InputConstants$Type.m_84899_(InputConstants.java)
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.platform.InputConstants$Type.<clinit>(InputConstants.java:214)
	at TRANSFORMER/oculus@1.6.15a/net.coderbot.iris.Iris.<clinit>(Iris.java:95)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.SystemReport.handler$zia000$fillSystemDetails(SystemReport.java:523)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.SystemReport.<init>(SystemReport.java:58)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.CrashReport.<init>(CrashReport.java:31)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.CrashReport.m_127529_(CrashReport.java:216)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:149)
	... 15 more
Caused by: java.lang.IllegalArgumentException: Not bootstrapped (called from registry ResourceKey[minecraft:root / minecraft:root])
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.m_179916_(Bootstrap.java:113)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.m_179912_(Bootstrap.java:106)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.MappedRegistry.<init>(MappedRegistry.java:85)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.MappedRegistry.<init>(MappedRegistry.java:81)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.registries.BuiltInRegistries.<clinit>(BuiltInRegistries.java:113)
	... 35 more
```

**Comment by squimbo** [comment]
Can confirm

**Comment by squimbo** [comment]
huh..?

**Comment by dima-dencep** [comment]
Duplicate of #548
