### ISSUE TITLE
[1.20.1] Crash: Buffer mapping is already disposed

### ISSUE THREAD

**Issue by BelgianDev** [Asek3/Oculus#652]
### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.7.0.jar

### Rubidium / Embeddium Version

embeddium-0.3.20+mc1.20.1.jar

### Operating System

Arch Linux

### What is your GPU?

Nvidia Geforce GTX 1650

### Java Version

Java-17-OpenJDK

### Reproduction Steps

The bug seems to happen at random, it crashes sometimes with the inventory open or just wandering in the world.

- Join a world
- Wait for it to happen.

### Crash Report file and latest.log
[Crash Report](https://gist.github.com/Raft08/e05b4ea7c0b1d021ed49b16b6da969df)
[Latest Log](https://gist.github.com/Raft08/72323ef5e4957e1addad3aba1e1fb2b4)

### Additional context

GeckoLib may be at play here too. for some reason I can't get the it in the log but GDLauncher's logs it displays these messages.

```
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList$SubList.get(ArrayList.java:1149)
	at TRANSFORMER/mclib@20/com.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:306)
	at TRANSFORMER/mclib@20/com.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:309)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.core.molang.MolangParser.parseSymbolsMolang(MolangParser.java:254)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.core.molang.MolangParser.parseOneLine(MolangParser.java:242)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.core.molang.MolangParser.parseExpression(MolangParser.java:197)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.core.molang.MolangParser.parseJson(MolangParser.java:179)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.loading.json.typeadapter.BakedAnimationsAdapter.buildKeyframeStack(BakedAnimationsAdapter.java:177)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.loading.json.typeadapter.BakedAnimationsAdapter.bakeBoneAnimations(BakedAnimationsAdapter.java:72)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.loading.json.typeadapter.BakedAnimationsAdapter.bakeAnimation(BakedAnimationsAdapter.java:53)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.loading.json.typeadapter.BakedAnimationsAdapter.deserialize(BakedAnimationsAdapter.java:39)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.loading.json.typeadapter.BakedAnimationsAdapter.deserialize(BakedAnimationsAdapter.java:31)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.fromJson(Gson.java:1214)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.fromJson(Gson.java:1319)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.fromJson(Gson.java:1261)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.loading.FileLoader.loadAnimationsFile(FileLoader.java:28)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.cache.GeckoLibCache.lambda$loadAnimations$1(GeckoLibCache.java:91)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.cache.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:123)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
software.bernie.geckolib.core.molang.MolangException: Couldn't parse '-35-' expression!
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.core.molang.MolangParser.parseOneLine(MolangParser.java:245)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.core.molang.MolangParser.parseExpression(MolangParser.java:197)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.core.molang.MolangParser.parseJson(MolangParser.java:179)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.loading.json.typeadapter.BakedAnimationsAdapter.buildKeyframeStack(BakedAnimationsAdapter.java:177)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.loading.json.typeadapter.BakedAnimationsAdapter.bakeBoneAnimations(BakedAnimationsAdapter.java:72)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.loading.json.typeadapter.BakedAnimationsAdapter.bakeAnimation(BakedAnimationsAdapter.java:53)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.loading.json.typeadapter.BakedAnimationsAdapter.deserialize(BakedAnimationsAdapter.java:39)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.loading.json.typeadapter.BakedAnimationsAdapter.deserialize(BakedAnimationsAdapter.java:31)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.fromJson(Gson.java:1214)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.fromJson(Gson.java:1319)
	at MC-BOOTSTRAP/com.google.gson@2.10/com.google.gson.Gson.fromJson(Gson.java:1261)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.loading.FileLoader.loadAnimationsFile(FileLoader.java:28)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.cache.GeckoLibCache.lambda$loadAnimations$1(GeckoLibCache.java:91)
	at TRANSFORMER/geckolib@4.4.6/software.bernie.geckolib.cache.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:123)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
java.lang.NullPointerException: in is null
	at java.base/java.util.zip.ZipInputStream.
```

**Comment by JT42JT42** [comment]
i have the same problem!
need help to
