### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by FatalDarknessReal** [Asek3/Oculus#673]
### Minecraft Version

1.20.1 Forge

### Oculus Version

oculus-mc1.20.1-1.7.0.jar

### Rubidium / Embeddium Version

embeddium-0.3.28+mc1.20.1

### Operating System

Windows 10

### What is your GPU?

AMD Radeon(TM) Vega 3 Graphics

### Java Version

Java 

### Reproduction Steps

Boot into the game with my mods idk

### Crash Report file and latest.log

```shell
Picked up _JAVA_OPTIONS: 
2024-08-10 10:17:07,852 main WARN Advanced terminal features are not available in this environment
[10:17:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, fataldarkness, --version, Forge 1.20.1, --gameDir, F:\Games\Minecraft\game\home\Forge 1.20.1, --assetsDir, F:\Games\Minecraft\game\assets, --assetIndex, 5, --uuid, 3250382ea294491a8722a16db435d43d, --accessToken, ????????, --clientId, , --xuid, , --userType, mojang, --versionType, modified, --width, 925, --height, 530, --launchTarget, forgeclient, --fml.forgeVersion, 47.3.5, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[10:17:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 22.0.1 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
[10:17:10] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
[10:17:10] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[10:17:11] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6
[10:17:11] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/F:/Games/Minecraft/game/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23100!/ Service=ModLauncher Env=CLIENT
[10:17:12] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: AMD Radeon(TM) Vega 3 Graphics GL version 4.6.148202 Core Profile Forward-Compatible Context 21.3.1 27.20.15003.1004, ATI Technologies Inc.
[10:17:13] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file F:\Games\Minecraft\game\libraries\net\minecraftforge\fmlcore\1.20.1-47.3.5\fmlcore-1.20.1-47.3.5.jar is missing mods.toml file
[10:17:13] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file F:\Games\Minecraft\game\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.3.5\javafmllanguage-1.20.1-47.3.5.jar is missing mods.toml file
[10:17:13] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file F:\Games\Minecraft\game\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.3.5\lowcodelanguage-1.20.1-47.3.5.jar is missing mods.toml file
[10:17:13] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file F:\Games\Minecraft\game\libraries\net\minecraftforge\mclanguage\1.20.1-47.3.5\mclanguage-1.20.1-47.3.5.jar is missing mods.toml file
[10:17:14] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select two dependency jars from JarJar which have the same identification: Mod File:  and Mod File: . Using Mod File: 
[10:17:14] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 19 dependencies adding them to mods collection
Exception in thread "main" java.lang.module.ResolutionException: Modules luaj.jse and luaj.jse.figura export package org.luaj.vm2.ast to module xaerozoomout
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:814)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:735)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
```

**Comment by dima-dencep** [comment]
Not an oculus bug
