### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by sayersr1** [Asek3/Oculus#674]
### Minecraft Version

1.20.1

### Oculus Version

1.7.0

### Rubidium / Embeddium Version

0.3.29

### Operating System

windows 11

### What is your GPU?

amd 6650 xt

### Java Version

java for 1.20.1?

### Reproduction Steps

start server 
crashes
https://control.sparkedhost.us/server/bca22c01/files/edit#/crash-reports/crash-2024-08-13_23.48.19-fml.txt

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-08-13 23:48:19
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.3.5-universal.jar%23184!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:37) ~[forge-1.20.1-47.3.5-universal.jar%23184!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23179!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Suspected Mods: NONE
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:1.0] {}
-- MOD oculus --
Details:
	Mod File: /home/container/mods/GchcoXML-vVuYfukI.Oculus.jar
	Failure message: Oculus (oculus) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
	Mod Version: 1.7.0
	Mod Issue URL: https://github.com/Asek3/Oculus/issues
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source) ~[?:?] {re:mixin}
	at java.lang.Class.getConstructor0(Unknown Source) ~[?:?] {re:mixin}
	at java.lang.Class.getDeclaredConstructor(Unknown Source) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.5.jar%23181!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.5.jar%23180!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.15.0-67-generic
	Java Version: 17.0.9, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 166745824 bytes (159 MiB) / 725614592 bytes (692 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 3
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 12
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 68456.92
	Virtual memory used (MB): 86154.27
	Swap memory total (MB): 4091.00
	Swap memory used (MB): 2417.38
	JVM Flags: 2 total; -Xms128M -Xmx6144M
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.5.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		kotlinforforge@4.11.0
		javafml@null
		lowcodefml@null
	Mod List: 
		mSQF1NpT-AlHVXgYe.Elytra Slot.jar                 |Elytra Slot                   |elytraslot                    |6.4.3+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		kuma-api-forge-20.1.8+1.20.1.jar                  |KumaAPI                       |kuma_api                      |20.1.8              |COMMON_SET|Manifest: NOSIGNATURE
		u6dRKJwZ-SR7MOWw2.Just Enough Items.jar           |Just Enough Items             |jei                           |15.12.2.48          |COMMON_SET|Manifest: NOSIGNATURE
		EZxoN8vL-CNrRqwvg.Additional Blocks: Vertical Edit|Additional Blocks: Vertical Ed|abverticaledition             |1.0.3b              |COMMON_SET|Manifest: NOSIGNATURE
		40FYwb4z-mRry0DgY.Caelus API.jar                  |Caelus API                    |caelus                        |3.2.0+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		7uh75ruZ-aG4T8pjo.KleeSlabs.jar                   |KleeSlabs                     |kleeslabs                     |15.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		LOpKHB2A-Rbp8Hzck.Waystones.jar                   |Waystones                     |waystones                     |14.1.4              |COMMON_SET|Manifest: NOSIGNATURE
		kVa5y52B-ubFv4wGb.Glassential (Forge).jar         |Glassential                   |glassential                   |1.20.1-1.2.6        |COMMON_SET|Manifest: NOSIGNATURE
		Wnxd13zP-nAHGB5ls.Clumps.jar                      |Clumps                        |clumps                        |12.0.0.4            |COMMON_SET|Manifest: NOSIGNATURE
		rlloIFEV-FDqFhZfz.Traveler's Backpack.jar         |Traveler's Backpack           |travelersbackpack             |9.1.15              |COMMON_SET|Manifest: NOSIGNATURE
		fPetb5Kh-Og40jCNX.Nature's Compass.jar            |Nature's Compass              |naturescompass                |1.20.1-1.11.2-forge |COMMON_SET|Manifest: NOSIGNATURE
		mixinextras-forge-0.3.5.jar                       |MixinExtras                   |mixinextras                   |0.3.5               |COMMON_SET|Manifest: NOSIGNATURE
		MBAkmtvl-WyhvCQj3.Balm.jar                        |Balm                          |balm                          |7.3.6               |COMMON_SET|Manifest: NOSIGNATURE
		p19vrgc2-oA5jxU4i.Fusion (Connected Textures).jar |Fusion                        |fusion                        |1.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		9s6osm5g-nr1znv5v.Cloth Config API.jar            |Cloth Config v10 API          |cloth_config                  |11.1.118            |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.20.1-47.3.5-universal.jar                 |Forge                         |forge                         |47.3.5              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		mQWkB9ON-O5D7DMz0.Stack Refill.jar                |Stack Refill                  |stackrefill                   |4.5                 |COMMON_SET|Manifest: NOSIGNATURE
		sk9rgfiA-vCML9MtQ.Embeddium.jar                   |Embeddium                     |embeddium                     |0.3.29+mc1.20.1     |COMMON_SET|Manifest: NOSIGNATURE
		Gv3VVf1s-wcjzR0vi.Why stacks of 16?.jar           |Why stacks of 16?             |wso16                         |1.1                 |COMMON_SET|Manifest: NOSIGNATURE
		b1ZV3DIJ-DULOQFj7.Athena.jar                      |Athena                        |athena                        |3.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		XpzGz7KD-Wf6ShWf5.Elytra Trims.jar                |Elytra Trims                  |elytratrims                   |3.4.4               |COMMON_SET|Manifest: NOSIGNATURE
		BAscRYKm-gfGw4ln2.Chipped.jar                     |Chipped                       |chipped                       |3.0.6               |COMMON_SET|Manifest: NOSIGNATURE
		server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: NOSIGNATURE
		P4FVY4ll-YznbGnc8.Simply Harvesting.jar           |Simply Harvesting             |simplyharvesting              |1.20.1-2.1.1        |COMMON_SET|Manifest: NOSIGNATURE
		Tl8ESrhX-xNEQid1X.TorchMaster.jar                 |Torchmaster                   |torchmaster                   |20.1.6              |COMMON_SET|Manifest: NOSIGNATURE
		kkmrDlKT-HI0iCUpi.TerraBlender.jar                |TerraBlender                  |terrablender                  |3.0.1.7             |COMMON_SET|Manifest: NOSIGNATURE
		HXF82T3G-peO5lWzX.Biomes O' Plenty.jar            |Biomes O' Plenty              |biomesoplenty                 |18.0.0.598          |COMMON_SET|Manifest: NOSIGNATURE
		mixinsquared-forge-0.1.2-beta.6.jar               |MixinSquared                  |mixinsquared                  |0.1.2-beta.6        |COMMON_SET|Manifest: NOSIGNATURE
		nvQzSEkH-MLYKnVCk.Jade 🔍.jar                     |Jade                          |jade                          |11.9.4+forge        |COMMON_SET|Manifest: NOSIGNATURE
		yPlaLxD1-fGEswUMR.Iron Furnaces.jar               |Iron Furnaces                 |ironfurnaces                  |4.1.6               |COMMON_SET|Manifest: NOSIGNATURE
		6FtRfnLg-VH8QpKA5.Do a Barrel Roll.jar            |Do a Barrel Roll              |do_a_barrel_roll              |3.5.6+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		kffmod-4.11.0.jar                                 |Kotlin For Forge              |kotlinforforge                |4.11.0              |COMMON_SET|Manifest: NOSIGNATURE
		Kaov2qgi-xXcXQ3Xm.Easy Villagers.jar              |Easy Villagers                |easy_villagers                |1.20.1-1.1.16       |COMMON_SET|Manifest: NOSIGNATURE
		vvuO3ImH-moWmAnjY.Curios API.jar                  |Curios API                    |curios                        |5.9.1+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-forge-1.20.1-0.6.10-7.jar                |Flywheel                      |flywheel                      |0.6.10-7            |COMMON_SET|Manifest: NOSIGNATURE
		LNytGWDc-HNYrbfZZ.Create.jar                      |Create                        |create                        |0.5.1.f             |COMMON_SET|Manifest: NOSIGNATURE
		GchcoXML-vVuYfukI.Oculus.jar                      |Oculus                        |oculus                        |1.7.0               |ERROR     |Manifest: NOSIGNATURE
		n2de3t2z-BlgpMWjV.Iron Chests: Restocked.jar      |Iron Chests: Restocked        |ironchests                    |5.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		e0M1UDsY-vddVmQmc.Collective.jar                  |Collective                    |collective                    |7.81                |COMMON_SET|Manifest: NOSIGNATURE
		ODQeqCgz-Rh4rH5QS.Ore Excavation.jar              |OreExcavation                 |oreexcavation                 |1.13.170            |COMMON_SET|Manifest: NOSIGNATURE
		G1hIVOrD-e8oxp0Cl.Resourceful Lib.jar             |Resourceful Lib               |resourcefullib                |2.1.28              |COMMON_SET|Manifest: NOSIGNATURE
		bV2crgLh-XCgKj8gL.Construction Wand.jar           |Construction Wand             |constructionwand              |1.20.1-2.11         |COMMON_SET|Manifest: NOSIGNATURE
		lhGA9TYQ-1MKTLiiG.Architectury API.jar            |Architectury                  |architectury                  |9.2.14              |COMMON_SET|Manifest: NOSIGNATURE
		EltpO5cN-ZqSHctHT.Lootr.jar                       |Lootr                         |lootr                         |0.7.34.85           |COMMON_SET|Manifest: NOSIGNATURE
		conditional-mixin-forge-0.6.2.jar                 |conditional mixin             |conditional_mixin             |0.6.2               |COMMON_SET|Manifest: NOSIGNATURE
		u7CFIOJ1-ZfQmT7WH.Twerk Crop Growth.jar           |Twerk Crop Growth             |twerkcropgrowth               |2.1.0               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: e403cb95-49b3-4061-83ae-31a6a47c082c
	FML: 47.3
	Forge: net.minecraftforge:47.3.5
```

**Comment by dima-dencep** [comment]
oculus is client only
