### ISSUE TITLE
Flywheel failing to load

### ISSUE THREAD

**Issue by druidicmage** [Asek3/Oculus#69]
### Minecraft Version

18.1

### Iris Version

oculus-mc1.18.1-1.2.1.jar

### Sodium Version

rubidium-0.5.0.jar

### Operating System

Windows 11

### What is your GPU?

GenuineIntel Intel(R) Core(TM) i5-9300H

### Java Version

Java 16

### Reproduction Steps

1. Boot Game
2. Load
3. Crash

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 4/29/22, 1:09 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.1-39.1.2-universal.jar%23102!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:169) ~[forge-1.18.1-39.1.2-universal.jar%23102!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:554) ~[client-1.18.1-20211210.034407-srg.jar%2398!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.oculus.json:MixinMinecraft,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineDestruction,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:409) ~[client-1.18.1-20211210.034407-srg.jar%2398!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:548) ~[client-1.18.1-20211210.034407-srg.jar%2398!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.oculus.json:MixinMinecraft,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineDestruction,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.18.1-20211210.034407-srg.jar%2398!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:875) ~[client-1.18.1-20211210.034407-srg.jar%2398!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1041) ~[client-1.18.1-20211210.034407-srg.jar%2398!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.oculus.json:MixinMinecraft,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineDestruction,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:661) ~[client-1.18.1-20211210.034407-srg.jar%2398!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:mixins.oculus.json:MixinMinecraft,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineDestruction,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2398!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.1.2.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.coderbot.iris.compat.flywheel.FlywheelCompat.disableBackend(FlywheelCompat.java:11) ~[oculus-mc1.18.1-1.2.1.jar%2381!/:1.0] {re:classloading}
-- MOD oculus --
Details:
	Mod File: oculus-mc1.18.1-1.2.1.jar
	Failure message: Oculus (oculus) encountered an error during the sided_setup event phase
		java.lang.NoSuchMethodError: 'void com.jozufozu.flywheel.config.FlwEngine.handle(com.jozufozu.flywheel.config.FlwEngine)'
	Mod Version: 1.2.1
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchMethodError: 'void com.jozufozu.flywheel.config.FlwEngine.handle(com.jozufozu.flywheel.config.FlwEngine)'
Stacktrace:
	at net.coderbot.iris.compat.flywheel.FlywheelCompat.disableBackend(FlywheelCompat.java:11) ~[oculus-mc1.18.1-1.2.1.jar%2381!/:1.0] {re:classloading}
	at net.coderbot.iris.Iris.onInitializeClient(Iris.java:103) ~[oculus-mc1.18.1-1.2.1.jar%2381!/:1.0] {re:mixin,re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.18.1-39.1.2.jar%23100!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.18.1-39.1.2.jar%2399!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 575286048 bytes (548 MiB) / 2260729856 bytes (2156 MiB) up to 6543114240 bytes (6240 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: DriverVersion=26.20.100.6911
	Graphics card #1 name: NVIDIA GeForce GTX 1650
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f91
	Graphics card #1 versionInfo: DriverVersion=30.0.15.1179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 31581.05
	Virtual memory used (MB): 18840.66
	Swap memory total (MB): 23552.00
	Swap memory used (MB): 2935.23
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6240m -Xms256m
	Loaded Shaderpack: (off)
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |ENQUEUE_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		radon-0.8.1.jar                                   |Radon                         |radon                         |0.8.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		FarmersDelight-1.18.1-1.0.4.jar                   |Farmer's Delight              |farmersdelight                |1.18.1-1.0.4        |ENQUEUE_IM|Manifest: NOSIGNATURE
		easy_mob_farm_1.18.1-0.4.0.jar                    |Easy Mob Farm                 |easy_mob_farm                 |0.4.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Voodoo-1.18.1-1.0.2.jar                           |Voodoo                        |voodoo                        |1.0.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		radium-0.7.7g.jar                                 |Radium                        |radium                        |0.7.7g              |ENQUEUE_IM|Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.18.1-9.0.13.jar   |EnchantmentDescriptions       |enchdesc                      |9.0.13              |ENQUEUE_IM|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |ENQUEUE_IM|Manifest: NOSIGNATURE
		EnigmaticGraves-1.18.1-1.7.4.jar                  |Enigmatic Graves              |enigmaticgraves               |1.18.1-1.7.4        |ENQUEUE_IM|Manifest: NOSIGNATURE
		Origins-1.18.1-1.3.2.1-unified.jar                |Additional Entity Attributes  |additionalentityattributes    |1.18.1-1.3.2.1      |ENQUEUE_IM|Manifest: NOSIGNATURE
		material_elements_1.18.1-3.1.0.jar                |Material Elements             |material_elements             |3.1.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		jei-1.18.1-9.4.1.172.jar                          |Just Enough Items             |jei                           |9.4.1.172           |ENQUEUE_IM|Manifest: NOSIGNATURE
		Pehkui-3.2.0+1.18.1-forge.jar                     |Pehkui                        |pehkui                        |3.2.0+1.18.1-forge  |ENQUEUE_IM|Manifest: NOSIGNATURE
		caelus-forge-1.18.1-3.0.0.2.jar                   |Caelus API                    |caelus                        |1.18.1-3.0.0.2      |ENQUEUE_IM|Manifest: NOSIGNATURE
		trofers-1.18.1-2.6.0.jar                          |Trofers                       |trofers                       |1.18.1-2.6.0        |ENQUEUE_IM|Manifest: NOSIGNATURE
		majrusz-library-1.18.1-2.7.1.jar                  |Majrusz Library               |majrusz_library               |2.7.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		rubidium-0.5.0.jar                                |Rubidium                      |rubidium                      |0.5.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		InsaneLib-1.4.3-mc1.18.1.jar                      |InsaneLib                     |insanelib                     |1.4.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.6.1.jar                     |Flywheel                      |flywheel                      |1.18-0.6.1.63       |ENQUEUE_IM|Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.6.2.jar                   |Curios API                    |curios                        |1.18.1-5.0.6.2      |ENQUEUE_IM|Manifest: NOSIGNATURE
		Patchouli-1.18.1-65.jar                           |Patchouli                     |patchouli                     |1.18.1-65           |ENQUEUE_IM|Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4f.jar                         |Create                        |create                        |0.4f                |ENQUEUE_IM|Manifest: NOSIGNATURE
		oculus-mc1.18.1-1.2.1.jar                         |Oculus                        |oculus                        |1.2.1               |ERROR     |Manifest: NOSIGNATURE
		XaerosWorldMap_1.20.3.1_Forge_1.18.jar            |Xaero's World Map             |xaeroworldmap                 |1.20.3.1            |ENQUEUE_IM|Manifest: NOSIGNATURE
		Controlling-forge-1.18.1-9.0+15.jar               |Controlling                   |controlling                   |9.0+15              |ENQUEUE_IM|Manifest: NOSIGNATURE
		JustEnoughProfessions-1.18-1.2.2.jar              |Just Enough Professions (JEP) |justenoughprofessions         |1.2.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |ENQUEUE_IM|Manifest: NOSIGNATURE
		Auto-Smelt-1.18.1-1.1.jar                         |Auto-Smelt                    |autosmelt                     |1.1                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		SereneSeasons-1.18.1-6.0.0.10-universal.jar       |Serene Seasons                |sereneseasons                 |1.18.1-6.0.0.10     |ENQUEUE_IM|Manifest: NOSIGNATURE
		upgradednetherite_items-1.18.1-3.1.0.2-release.jar|Upgraded Netherite : Items    |upgradednetherite_items       |1.18.1-3.1.0.2-relea|ENQUEUE_IM|Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.18.1-3.15.15.550.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.1-3.15.15.550  |ENQUEUE_IM|Manifest: NOSIGNATURE
		upgradedcore-1.18.1-3.1.0.0-release.jar           |Upgraded Core                 |upgradedcore                  |1.18.1-3.1.0.0-relea|ENQUEUE_IM|Manifest: NOSIGNATURE
		majruszs-difficulty-1.18.1-1.4.1.jar              |Majrusz's Progressive Difficul|majruszs_difficulty           |1.4.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		ProgressiveBosses-3.5.4-mc1.18.1.jar              |Progressive Bosses            |progressivebosses             |3.5.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		ferritecore-4.1.2-forge.jar                       |Ferrite Core                  |ferritecore                   |4.1.2               |ENQUEUE_IM|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		JustEnoughResources-1.18.1-0.13.1.141.jar         |Just Enough Resources         |jeresources                   |0.13.1.141          |ENQUEUE_IM|Manifest: NOSIGNATURE
		3dskinlayers-forge-1.4.4-mc1.18.2.jar             |3dSkinLayers                  |skinlayers3d                  |1.4.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.18.1-39.1.2-universal.jar                 |Forge                         |forge                         |39.1.2              |ENQUEUE_IM|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Quark-3.1-340.jar                                 |Quark                         |quark                         |3.1-340             |ENQUEUE_IM|Manifest: NOSIGNATURE
		geckolib-1.18-forge-3.0.11.jar                    |GeckoLib                      |geckolib3                     |3.0.11              |ENQUEUE_IM|Manifest: NOSIGNATURE
		ars_nouveau-1.18.1-2.3.1.jar                      |Ars Nouveau                   |ars_nouveau                   |2.3.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		ars_elemental-1.18.1-0.3.0.5.jar                  |Ars Elemental                 |ars_elemental                 |1.18.1-0.3.0.5      |ENQUEUE_IM|Manifest: NOSIGNATURE
		ars_creo-1.18.1-1.0.0-BETA1.jar                   |Example Mod                   |ars_creo                      |1.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		enchanting_overhauled-1.0.6.jar                   |Enchanting Overhauled         |enchanting_overhauled         |1.0.6               |ENQUEUE_IM|Manifest: NOSIGNATURE
		cosmosportals-1.18.1-3.1.5.80-universal.jar       |Cosmos Portals                |cosmosportals                 |3.1.5.80            |ENQUEUE_IM|Manifest: NOSIGNATURE
		upgradednetherite-1.18.1-4.1.0.0-release.jar      |Upgraded Netherite            |upgradednetherite             |1.18.1-4.1.0.0-relea|ENQUEUE_IM|Manifest: NOSIGNATURE
		DungeonsArise-1.18.1-2.1.49d-beta.jar             |When Dungeons Arise           |dungeons_arise                |2.1.49d-1.18.1      |ENQUEUE_IM|Manifest: NOSIGNATURE
		cosmoslibrary-1.18.1-5.1.8.10-universal.jar       |Cosmos Library                |cosmoslibrary                 |5.1.8.10            |ENQUEUE_IM|Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: db4b7d7b-664a-426f-94e8-5e4aa7328a0e
	FML: 39.1
	Forge: net.minecraftforge:39.1.2
```

### Additional context

flywheel-forge-1.18-0.6.1.jar
create-mc1.18.1_v0.4f.jar

**Comment by Asek3** [comment]
dude wtf u are using 1.18.1 update to 1.18.2
