### ISSUE TITLE
Bug in DEDICATED SERVER

### ISSUE THREAD

**Issue by Raukdv** [Asek3/Oculus#735]
### Minecraft Version

1.20.1

### Oculus Version

oculus-mc1.20.1-1.7.0.jar

### Rubidium / Embeddium Version

embeddium-0.3.31+mc1.20.1.jar 

### Operating System

Linux (amd64) version 5.4.0-189-generic

### What is your GPU?

AMD Ryzen 9 5900X 12-Core Processor

### Java Version

Java Version: 18, Oracle Corporation

### Reproduction Steps

Meanwhile load mods process from the server itself

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-12-08 23:04:29
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.3.0-universal.jar%23228!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:37) ~[forge-1.20.1-47.3.0-universal.jar%23228!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23223!/:?] {re:classloading}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.0.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.3.0.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.3.0.jar%2369!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Suspected Mods: NONE
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.3.0.jar%2369!/:1.0] {}
-- MOD oculus --
Details:
	Mod File: /home/minecraft/server/mods/oculus-mc1.20.1-1.7.0.jar
	Failure message: Oculus (oculus) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
	Mod Version: 1.7.0
	Mod Issue URL: https://github.com/Asek3/Oculus/issues
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.3.0.jar%2369!/:1.0] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] {}
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3405) ~[?:?] {re:mixin}
	at java.lang.Class.getConstructor0(Class.java:3610) ~[?:?] {re:mixin}
	at java.lang.Class.getDeclaredConstructor(Class.java:2786) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.0.jar%23225!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23224!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}


-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.4.0-189-generic
	Java Version: 18, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 403391520 bytes (384 MiB) / 964689920 bytes (920 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 6
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5900X 12-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: ASPEED Graphics Family
	Graphics card #0 vendor: ASPEED Technology, Inc. (0x1a03)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0x2000
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 64385.43
	Virtual memory used (MB): 1504.94
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 1 total; -Xmx6144m
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		kotori_scala@3.3.1-build-0
		javafml@null
	Mod List: 
		kuma-api-forge-20.1.8+1.20.1.jar                  |KumaAPI                       |kuma_api                      |20.1.8              |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.8-forge-mc1.20.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.8               |COMMON_SET|Manifest: NOSIGNATURE
		Cucumber-1.20.1-7.0.12.jar                        |Cucumber Library              |cucumber                      |7.0.12              |COMMON_SET|Manifest: NOSIGNATURE
		MutantMonsters-v8.0.7-1.20.1-Forge.jar            |Mutant Monsters               |mutantmonsters                |8.0.7               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		sophisticatedcore-1.20.1-0.6.34.718.jar           |Sophisticated Core            |sophisticatedcore             |0.6.34.718          |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.20-14.1.6.jar                   |Waystones                     |waystones                     |14.1.6              |COMMON_SET|Manifest: NOSIGNATURE
		laserio-1.6.8.jar                                 |LaserIO                       |laserio                       |1.6.8               |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.20.1-12.0.0.4.jar                  |Clumps                        |clumps                        |12.0.0.4            |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.20.1-5.10.3-forge.jar                |Journeymap                    |journeymap                    |5.10.3              |COMMON_SET|Manifest: NOSIGNATURE
		modernfix-forge-5.19.4+mc1.20.1.jar               |ModernFix                     |modernfix                     |5.19.4+mc1.20.1     |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.20.0.103.jar                  |Just Enough Items             |jei                           |15.20.0.103         |COMMON_SET|Manifest: NOSIGNATURE
		citadel-2.6.0-1.20.1.jar                          |Citadel                       |citadel                       |2.6.0               |COMMON_SET|Manifest: NOSIGNATURE
		Powah-5.0.7.jar                                   |Powah                         |powah                         |5.0.7               |COMMON_SET|Manifest: NOSIGNATURE
		BotanyPots-Forge-1.20.1-13.0.39.jar               |BotanyPots                    |botanypots                    |13.0.39             |COMMON_SET|Manifest: NOSIGNATURE
		mixinextras-forge-0.4.1.jar                       |MixinExtras                   |mixinextras                   |0.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		GlitchCore-forge-1.20.1-0.0.1.1.jar               |GlitchCore                    |glitchcore                    |0.0.1.1             |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.20.1-20.2.13.jar                |Bookshelf                     |bookshelf                     |20.2.13             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.20.1-3.20.11.1115.jar    |Sophisticated Backpacks       |sophisticatedbackpacks        |3.20.11.1115        |COMMON_SET|Manifest: NOSIGNATURE
		mcjtylib-1.20-8.0.6.jar                           |McJtyLib                      |mcjtylib                      |1.20-8.0.6          |COMMON_SET|Manifest: NOSIGNATURE
		rftoolsbase-1.20-5.0.5.jar                        |RFToolsBase                   |rftoolsbase                   |1.20-5.0.5          |COMMON_SET|Manifest: NOSIGNATURE
		xnet-1.20-6.1.6.jar                               |XNet                          |xnet                          |1.20-6.1.6          |COMMON_SET|Manifest: NOSIGNATURE
		GrimoireOfGaia4-1.20.1-4.0.0-alpha.11.jar         |Grimoire of Gaia 4            |grimoireofgaia                |4.0.0-alpha.11      |COMMON_SET|Manifest: NOSIGNATURE
		iceandfire-2.1.13-1.20.1-beta-5.jar               |Ice and Fire                  |iceandfire                    |2.1.13-1.20.1       |COMMON_SET|Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.3.9-all.jar                   |Balm                          |balm                          |7.3.9               |COMMON_SET|Manifest: NOSIGNATURE
		FpsReducer2-forge-1.20-2.5.jar                    |FPS Reducer                   |fpsreducer                    |1.20-2.5            |COMMON_SET|Manifest: NOSIGNATURE
		memoryleakfix-forge-1.17+-1.1.5.jar               |Memory Leak Fix               |memoryleakfix                 |1.1.5               |COMMON_SET|Manifest: NOSIGNATURE
		puzzlesaccessapi-forge-8.0.7.jar                  |Puzzles Access Api            |puzzlesaccessapi              |8.0.7               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		cloth-config-11.1.136-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.136            |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.20.1-47.3.0-universal.jar                 |Forge                         |forge                         |47.3.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		refinedstorage-1.12.4.jar                         |Refined Storage               |refinedstorage                |1.12.4              |COMMON_SET|Manifest: NOSIGNATURE
		embeddium-0.3.31+mc1.20.1.jar                     |Embeddium                     |embeddium                     |0.3.31+mc1.20.1     |COMMON_SET|Manifest: NOSIGNATURE
		MysticalAgriculture-1.20.1-7.0.14.jar             |Mystical Agriculture          |mysticalagriculture           |7.0.14              |COMMON_SET|Manifest: NOSIGNATURE
		ironchest-1.20.1-14.4.4.jar                       |Iron Chests                   |ironchest                     |1.20.1-14.4.4       |COMMON_SET|Manifest: NOSIGNATURE
		server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: NOSIGNATURE
		industrial-foregoing-1.20.1-3.5.19.jar            |Industrial Foregoing          |industrialforegoing           |3.5.19              |COMMON_SET|Manifest: NOSIGNATURE
		torchmaster-20.1.8.jar                            |Torchmaster                   |torchmaster                   |20.1.8              |COMMON_SET|Manifest: NOSIGNATURE
		voicechat-forge-1.20.1-2.5.24.jar                 |Simple Voice Chat             |voicechat                     |1.20.1-2.5.24       |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.20.1-3.0.1.7.jar             |TerraBlender                  |terrablender                  |3.0.1.7             |COMMON_SET|Manifest: NOSIGNATURE
		titanium-1.20.1-3.8.32.jar                        |Titanium                      |titanium                      |3.8.32              |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-forge-1.20.1-19.0.0.91.jar          |Biomes O' Plenty              |biomesoplenty                 |19.0.0.91           |COMMON_SET|Manifest: NOSIGNATURE
		Jade-1.20.1-Forge-11.12.1.jar                     |Jade                          |jade                          |11.12.1+forge       |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.17a-forge-mc1.20.1.jar |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.17+a            |COMMON_SET|Manifest: NOSIGNATURE
		lionfishapi-1.9.jar                               |LionfishAPI                   |lionfishapi                   |1.9                 |COMMON_SET|Manifest: NOSIGNATURE
		largefluidtank-forge-20.7.5.jar                   |Fluid Tank                    |fluidtank                     |20.7.5              |COMMON_SET|Manifest: ef:50:af:b3:03:e0:3e:70:a7:ef:78:77:a5:4d:d4:b5:07:ec:df:9d:d6:f3:12:13:c9:3c:cd:9a:0a:3e:6b:43
		L_Enders_Cataclysm-2.14 - 1.20.1.jar              |Cataclysm Mod                 |cataclysm                     |2.14                |COMMON_SET|Manifest: NOSIGNATURE
		ec_lec_plugin-1.20.1-2.0.2-all.jar                |EC L_Ender's Cataclysm Plugin |ec_lec_plugin                 |2.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-5.10.0+1.20.1.jar                    |Curios API                    |curios                        |5.10.0+1.20.1       |COMMON_SET|Manifest: NOSIGNATURE
		Mekanism-1.20.1-10.4.9.61.jar                     |Mekanism                      |mekanism                      |10.4.9              |COMMON_SET|Manifest: NOSIGNATURE
		MekanismGenerators-1.20.1-10.4.9.61.jar           |Mekanism: Generators          |mekanismgenerators            |10.4.9              |COMMON_SET|Manifest: NOSIGNATURE
		MekanismAdditions-1.20.1-10.4.9.61.jar            |Mekanism: Additions           |mekanismadditions             |10.4.9              |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.20.1-83-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-83-FORGE     |COMMON_SET|Manifest: NOSIGNATURE
		oculus-mc1.20.1-1.7.0.jar                         |Oculus                        |oculus                        |1.7.0               |ERROR     |Manifest: NOSIGNATURE
		StorageDrawers-1.20.1-12.9.9.jar                  |Storage Drawers               |storagedrawers                |12.9.9              |COMMON_SET|Manifest: NOSIGNATURE
		ImmediatelyFast-Forge-1.3.0+1.20.4.jar            |ImmediatelyFast               |immediatelyfast               |1.3.0+1.20.4        |COMMON_SET|Manifest: NOSIGNATURE
		MekanismTools-1.20.1-10.4.9.61.jar                |Mekanism: Tools               |mekanismtools                 |10.4.9              |COMMON_SET|Manifest: NOSIGNATURE
		architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |COMMON_SET|Manifest: NOSIGNATURE
		ferritecore-6.0.1-forge.jar                       |Ferrite Core                  |ferritecore                   |6.0.1               |COMMON_SET|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		PuzzlesLib-v8.1.24-1.20.1-Forge.jar               |Puzzles Lib                   |puzzleslib                    |8.1.24              |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		trashcans-1.0.18a-forge-mc1.20.jar                |Trash Cans                    |trashcans                     |1.0.18a             |COMMON_SET|Manifest: NOSIGNATURE
		framework-forge-1.20.1-0.7.11.jar                 |Framework                     |framework                     |0.7.11              |COMMON_SET|Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		FallingTree-1.20.1-4.3.4.jar                      |FallingTree                   |fallingtree                   |4.3.4               |COMMON_SET|Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		CodeChickenLib-1.20.1-4.4.0.516-universal.jar     |CodeChicken Lib               |codechickenlib                |4.4.0.516           |COMMON_SET|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		BrandonsCore-1.20.1-3.2.1.302-universal.jar       |Brandon's Core                |brandonscore                  |3.2.1.302           |COMMON_SET|Manifest: 53:bb:a0:11:bd:61:e2:1a:e2:cb:fd:f8:4f:e4:cd:a5:cc:12:f4:43:f0:78:68:3b:e1:62:c6:78:3b:27:ff:fe
		Draconic-Evolution-1.20.1-3.1.2.588-universal.jar |Draconic Evolution            |draconicevolution             |3.1.2.588           |COMMON_SET|Manifest: 53:bb:a0:11:bd:61:e2:1a:e2:cb:fd:f8:4f:e4:cd:a5:cc:12:f4:43:f0:78:68:3b:e1:62:c6:78:3b:27:ff:fe
		expanded_combat-1.20.1-3.2.1-all.jar              |Expanded Combat               |expanded_combat               |3.2.1               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 25d44b09-24b9-4e6a-bec6-213c700c141f
	FML: 47.3
	Forge: net.minecraftforge:47.3.0
```

### Additional context

I am trying to setup a server in the ScalaCubes provider, and this is happen. It's help for solve this crash or someone has a better idea for this, go ahead.

**Comment by kakashi1464** [comment]
Oculus is a client side mod
